// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gotdbot

// AddMember is a helper method for Client.AddChatMember
func (c *Chat) AddMember(client *Client, forwardLimit int32, userId int64) (*FailedToAddMembers, error) {
	return client.AddChatMember(c.Id, forwardLimit, userId)
}

// AddMembers is a helper method for Client.AddChatMembers
func (c *Chat) AddMembers(client *Client, userIds []int64) (*FailedToAddMembers, error) {
	return client.AddChatMembers(c.Id, userIds)
}

// AddToList is a helper method for Client.AddChatToList
func (c *Chat) AddToList(client *Client, chatList ChatList) error {
	return client.AddChatToList(c.Id, chatList)
}

// AddChecklistTasks is a helper method for Client.AddChecklistTasks
func (c *Chat) AddChecklistTasks(client *Client, messageId int64, tasks []InputChecklistTask) error {
	return client.AddChecklistTasks(c.Id, messageId, tasks)
}

// AddFileToDownloads is a helper method for Client.AddFileToDownloads
func (c *Chat) AddFileToDownloads(client *Client, fileId int32, messageId int64, priority int32) (*File, error) {
	return client.AddFileToDownloads(c.Id, fileId, messageId, priority)
}

// AddLocalMessage is a helper method for Client.AddLocalMessage
func (c *Chat) AddLocalMessage(client *Client, disableNotification bool, inputMessageContent InputMessageContent, senderId MessageSender, opts *AddLocalMessageOpts) (*Message, error) {
	return client.AddLocalMessage(c.Id, disableNotification, inputMessageContent, senderId, opts)
}

// AddMessageReaction is a helper method for Client.AddMessageReaction
func (c *Chat) AddMessageReaction(client *Client, isBig bool, messageId int64, reactionType ReactionType, updateRecentReactions bool) error {
	return client.AddMessageReaction(c.Id, isBig, messageId, reactionType, updateRecentReactions)
}

// AddOffer is a helper method for Client.AddOffer
func (c *Chat) AddOffer(client *Client, messageId int64, options *MessageSendOptions) (*Message, error) {
	return client.AddOffer(c.Id, messageId, options)
}

// AddPendingPaidMessageReaction is a helper method for Client.AddPendingPaidMessageReaction
func (c *Chat) AddPendingPaidMessageReaction(client *Client, messageId int64, starCount int64, opts *AddPendingPaidMessageReactionOpts) error {
	return client.AddPendingPaidMessageReaction(c.Id, messageId, starCount, opts)
}

// AddRecentlyFound is a helper method for Client.AddRecentlyFoundChat
func (c *Chat) AddRecentlyFound(client *Client) error {
	return client.AddRecentlyFoundChat(c.Id)
}

// AddStoryAlbumStories is a helper method for Client.AddStoryAlbumStories
func (c *Chat) AddStoryAlbumStories(client *Client, storyAlbumId int32, storyIds []int32) (*StoryAlbum, error) {
	return client.AddStoryAlbumStories(c.Id, storyAlbumId, storyIds)
}

// ApproveSuggestedPost is a helper method for Client.ApproveSuggestedPost
func (c *Chat) ApproveSuggestedPost(client *Client, messageId int64, sendDate int32) error {
	return client.ApproveSuggestedPost(c.Id, messageId, sendDate)
}

// BanMember is a helper method for Client.BanChatMember
func (c *Chat) BanMember(client *Client, bannedUntilDate int32, memberId MessageSender, revokeMessages bool) error {
	return client.BanChatMember(bannedUntilDate, c.Id, memberId, revokeMessages)
}

// Boost is a helper method for Client.BoostChat
func (c *Chat) Boost(client *Client, slotIds []int32) (*ChatBoostSlots, error) {
	return client.BoostChat(c.Id, slotIds)
}

// CanPostStory is a helper method for Client.CanPostStory
func (c *Chat) CanPostStory(client *Client) (CanPostStoryResult, error) {
	return client.CanPostStory(c.Id)
}

// CheckUsername is a helper method for Client.CheckChatUsername
func (c *Chat) CheckUsername(client *Client, username string) (CheckChatUsernameResult, error) {
	return client.CheckChatUsername(c.Id, username)
}

// ClickAnimatedEmojiMessage is a helper method for Client.ClickAnimatedEmojiMessage
func (c *Chat) ClickAnimatedEmojiMessage(client *Client, messageId int64) (*Sticker, error) {
	return client.ClickAnimatedEmojiMessage(c.Id, messageId)
}

// ClickSponsoredMessage is a helper method for Client.ClickChatSponsoredMessage
func (c *Chat) ClickSponsoredMessage(client *Client, fromFullscreen bool, isMediaClick bool, messageId int64) error {
	return client.ClickChatSponsoredMessage(c.Id, fromFullscreen, isMediaClick, messageId)
}

// Close is a helper method for Client.CloseChat
func (c *Chat) Close(client *Client) error {
	return client.CloseChat(c.Id)
}

// CommitPendingPaidMessageReactions is a helper method for Client.CommitPendingPaidMessageReactions
func (c *Chat) CommitPendingPaidMessageReactions(client *Client, messageId int64) error {
	return client.CommitPendingPaidMessageReactions(c.Id, messageId)
}

// CreateInviteLink is a helper method for Client.CreateChatInviteLink
func (c *Chat) CreateInviteLink(client *Client, createsJoinRequest bool, expirationDate int32, memberLimit int32, name string) (*ChatInviteLink, error) {
	return client.CreateChatInviteLink(c.Id, createsJoinRequest, expirationDate, memberLimit, name)
}

// CreateSubscriptionInviteLink is a helper method for Client.CreateChatSubscriptionInviteLink
func (c *Chat) CreateSubscriptionInviteLink(client *Client, name string, subscriptionPricing *StarSubscriptionPricing) (*ChatInviteLink, error) {
	return client.CreateChatSubscriptionInviteLink(c.Id, name, subscriptionPricing)
}

// CreateForumTopic is a helper method for Client.CreateForumTopic
func (c *Chat) CreateForumTopic(client *Client, icon *ForumTopicIcon, isNameImplicit bool, name string) (*ForumTopicInfo, error) {
	return client.CreateForumTopic(c.Id, icon, isNameImplicit, name)
}

// CreateVideo is a helper method for Client.CreateVideoChat
func (c *Chat) CreateVideo(client *Client, isRtmpStream bool, startDate int32) (*GroupCallId, error) {
	return client.CreateVideoChat(c.Id, isRtmpStream, startDate, c.Title)
}

// DeclineGroupCallInvitation is a helper method for Client.DeclineGroupCallInvitation
func (c *Chat) DeclineGroupCallInvitation(client *Client, messageId int64) error {
	return client.DeclineGroupCallInvitation(c.Id, messageId)
}

// DeclineSuggestedPost is a helper method for Client.DeclineSuggestedPost
func (c *Chat) DeclineSuggestedPost(client *Client, comment string, messageId int64) error {
	return client.DeclineSuggestedPost(c.Id, comment, messageId)
}

// DeleteAllRevokedInviteLinks is a helper method for Client.DeleteAllRevokedChatInviteLinks
func (c *Chat) DeleteAllRevokedInviteLinks(client *Client, creatorUserId int64) error {
	return client.DeleteAllRevokedChatInviteLinks(c.Id, creatorUserId)
}

// Delete is a helper method for Client.DeleteChat
func (c *Chat) Delete(client *Client) error {
	return client.DeleteChat(c.Id)
}

// DeleteBackground is a helper method for Client.DeleteChatBackground
func (c *Chat) DeleteBackground(client *Client, restorePrevious bool) error {
	return client.DeleteChatBackground(c.Id, restorePrevious)
}

// DeleteHistory is a helper method for Client.DeleteChatHistory
func (c *Chat) DeleteHistory(client *Client, removeFromChatList bool, revoke bool) error {
	return client.DeleteChatHistory(c.Id, removeFromChatList, revoke)
}

// DeleteMessagesByDate is a helper method for Client.DeleteChatMessagesByDate
func (c *Chat) DeleteMessagesByDate(client *Client, maxDate int32, minDate int32, revoke bool) error {
	return client.DeleteChatMessagesByDate(c.Id, maxDate, minDate, revoke)
}

// DeleteMessagesBySender is a helper method for Client.DeleteChatMessagesBySender
func (c *Chat) DeleteMessagesBySender(client *Client, senderId MessageSender) error {
	return client.DeleteChatMessagesBySender(c.Id, senderId)
}

// DeleteReplyMarkup is a helper method for Client.DeleteChatReplyMarkup
func (c *Chat) DeleteReplyMarkup(client *Client, messageId int64) error {
	return client.DeleteChatReplyMarkup(c.Id, messageId)
}

// DeleteDirectMessagesTopicHistory is a helper method for Client.DeleteDirectMessagesChatTopicHistory
func (c *Chat) DeleteDirectMessagesTopicHistory(client *Client, topicId int64) error {
	return client.DeleteDirectMessagesChatTopicHistory(c.Id, topicId)
}

// DeleteDirectMessagesTopicMessagesByDate is a helper method for Client.DeleteDirectMessagesChatTopicMessagesByDate
func (c *Chat) DeleteDirectMessagesTopicMessagesByDate(client *Client, maxDate int32, minDate int32, topicId int64) error {
	return client.DeleteDirectMessagesChatTopicMessagesByDate(c.Id, maxDate, minDate, topicId)
}

// DeleteForumTopic is a helper method for Client.DeleteForumTopic
func (c *Chat) DeleteForumTopic(client *Client, forumTopicId int32) error {
	return client.DeleteForumTopic(c.Id, forumTopicId)
}

// DeleteMessages is a helper method for Client.DeleteMessages
func (c *Chat) DeleteMessages(client *Client, messageIds []int64, revoke bool) error {
	return client.DeleteMessages(c.Id, messageIds, revoke)
}

// DeleteRevokedInviteLink is a helper method for Client.DeleteRevokedChatInviteLink
func (c *Chat) DeleteRevokedInviteLink(client *Client, inviteLink string) error {
	return client.DeleteRevokedChatInviteLink(c.Id, inviteLink)
}

// DeleteStoryAlbum is a helper method for Client.DeleteStoryAlbum
func (c *Chat) DeleteStoryAlbum(client *Client, storyAlbumId int32) error {
	return client.DeleteStoryAlbum(c.Id, storyAlbumId)
}

// EditBusinessMessageCaption is a helper method for Client.EditBusinessMessageCaption
func (c *Chat) EditBusinessMessageCaption(client *Client, businessConnectionId string, messageId int64, showCaptionAboveMedia bool, opts *EditBusinessMessageCaptionOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageCaption(businessConnectionId, c.Id, messageId, showCaptionAboveMedia, opts)
}

// EditBusinessMessageChecklist is a helper method for Client.EditBusinessMessageChecklist
func (c *Chat) EditBusinessMessageChecklist(client *Client, businessConnectionId string, checklist *InputChecklist, messageId int64, opts *EditBusinessMessageChecklistOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageChecklist(businessConnectionId, c.Id, checklist, messageId, opts)
}

// EditBusinessMessageLiveLocation is a helper method for Client.EditBusinessMessageLiveLocation
func (c *Chat) EditBusinessMessageLiveLocation(client *Client, businessConnectionId string, heading int32, livePeriod int32, messageId int64, proximityAlertRadius int32, opts *EditBusinessMessageLiveLocationOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageLiveLocation(businessConnectionId, c.Id, heading, livePeriod, messageId, proximityAlertRadius, opts)
}

// EditBusinessMessageMedia is a helper method for Client.EditBusinessMessageMedia
func (c *Chat) EditBusinessMessageMedia(client *Client, businessConnectionId string, inputMessageContent InputMessageContent, messageId int64, opts *EditBusinessMessageMediaOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageMedia(businessConnectionId, c.Id, inputMessageContent, messageId, opts)
}

// EditBusinessMessageReplyMarkup is a helper method for Client.EditBusinessMessageReplyMarkup
func (c *Chat) EditBusinessMessageReplyMarkup(client *Client, businessConnectionId string, messageId int64, opts *EditBusinessMessageReplyMarkupOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageReplyMarkup(businessConnectionId, c.Id, messageId, opts)
}

// EditBusinessMessageText is a helper method for Client.EditBusinessMessageText
func (c *Chat) EditBusinessMessageText(client *Client, businessConnectionId string, inputMessageContent InputMessageContent, messageId int64, opts *EditBusinessMessageTextOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageText(businessConnectionId, c.Id, inputMessageContent, messageId, opts)
}

// EditInviteLink is a helper method for Client.EditChatInviteLink
func (c *Chat) EditInviteLink(client *Client, createsJoinRequest bool, expirationDate int32, inviteLink string, memberLimit int32, name string) (*ChatInviteLink, error) {
	return client.EditChatInviteLink(c.Id, createsJoinRequest, expirationDate, inviteLink, memberLimit, name)
}

// EditSubscriptionInviteLink is a helper method for Client.EditChatSubscriptionInviteLink
func (c *Chat) EditSubscriptionInviteLink(client *Client, inviteLink string, name string) (*ChatInviteLink, error) {
	return client.EditChatSubscriptionInviteLink(c.Id, inviteLink, name)
}

// EditForumTopic is a helper method for Client.EditForumTopic
func (c *Chat) EditForumTopic(client *Client, editIconCustomEmoji bool, forumTopicId int32, iconCustomEmojiId int64, name string) error {
	return client.EditForumTopic(c.Id, editIconCustomEmoji, forumTopicId, iconCustomEmojiId, name)
}

// EditMessageCaption is a helper method for Client.EditMessageCaption
func (c *Chat) EditMessageCaption(client *Client, messageId int64, showCaptionAboveMedia bool, opts *EditMessageCaptionOpts) (*Message, error) {
	return client.EditMessageCaption(c.Id, messageId, showCaptionAboveMedia, opts)
}

// EditMessageChecklist is a helper method for Client.EditMessageChecklist
func (c *Chat) EditMessageChecklist(client *Client, checklist *InputChecklist, messageId int64, opts *EditMessageChecklistOpts) (*Message, error) {
	return client.EditMessageChecklist(c.Id, checklist, messageId, opts)
}

// EditMessageLiveLocation is a helper method for Client.EditMessageLiveLocation
func (c *Chat) EditMessageLiveLocation(client *Client, heading int32, livePeriod int32, messageId int64, proximityAlertRadius int32, opts *EditMessageLiveLocationOpts) (*Message, error) {
	return client.EditMessageLiveLocation(c.Id, heading, livePeriod, messageId, proximityAlertRadius, opts)
}

// EditMessageMedia is a helper method for Client.EditMessageMedia
func (c *Chat) EditMessageMedia(client *Client, inputMessageContent InputMessageContent, messageId int64, opts *EditMessageMediaOpts) (*Message, error) {
	return client.EditMessageMedia(c.Id, inputMessageContent, messageId, opts)
}

// EditMessageReplyMarkup is a helper method for Client.EditMessageReplyMarkup
func (c *Chat) EditMessageReplyMarkup(client *Client, messageId int64, opts *EditMessageReplyMarkupOpts) (*Message, error) {
	return client.EditMessageReplyMarkup(c.Id, messageId, opts)
}

// EditMessageSchedulingState is a helper method for Client.EditMessageSchedulingState
func (c *Chat) EditMessageSchedulingState(client *Client, messageId int64, opts *EditMessageSchedulingStateOpts) error {
	return client.EditMessageSchedulingState(c.Id, messageId, opts)
}

// EditMessageText is a helper method for Client.EditMessageText
func (c *Chat) EditMessageText(client *Client, inputMessageContent InputMessageContent, messageId int64, opts *EditMessageTextOpts) (*Message, error) {
	return client.EditMessageText(c.Id, inputMessageContent, messageId, opts)
}

// ForwardMessages is a helper method for Client.ForwardMessages
func (c *Chat) ForwardMessages(client *Client, fromChatId int64, messageIds []int64, removeCaption bool, sendCopy bool, opts *ForwardMessagesOpts) (*Messages, error) {
	return client.ForwardMessages(c.Id, fromChatId, messageIds, removeCaption, sendCopy, opts)
}

// GetAllStickerEmojis is a helper method for Client.GetAllStickerEmojis
func (c *Chat) GetAllStickerEmojis(client *Client, query string, returnOnlyMainEmoji bool, stickerType StickerType) (*Emojis, error) {
	return client.GetAllStickerEmojis(c.Id, query, returnOnlyMainEmoji, stickerType)
}

// GetCallbackQueryAnswer is a helper method for Client.GetCallbackQueryAnswer
func (c *Chat) GetCallbackQueryAnswer(client *Client, messageId int64, payload CallbackQueryPayload) (*CallbackQueryAnswer, error) {
	return client.GetCallbackQueryAnswer(c.Id, messageId, payload)
}

// GetCallbackQueryMessage is a helper method for Client.GetCallbackQueryMessage
func (c *Chat) GetCallbackQueryMessage(client *Client, callbackQueryId int64, messageId int64) (*Message, error) {
	return client.GetCallbackQueryMessage(callbackQueryId, c.Id, messageId)
}

// Get is a helper method for Client.GetChat
func (c *Chat) Get(client *Client) (*Chat, error) {
	return client.GetChat(c.Id)
}

// GetActiveStories is a helper method for Client.GetChatActiveStories
func (c *Chat) GetActiveStories(client *Client) (*ChatActiveStories, error) {
	return client.GetChatActiveStories(c.Id)
}

// GetAdministrators is a helper method for Client.GetChatAdministrators
func (c *Chat) GetAdministrators(client *Client) (*ChatAdministrators, error) {
	return client.GetChatAdministrators(c.Id)
}

// GetArchivedStories is a helper method for Client.GetChatArchivedStories
func (c *Chat) GetArchivedStories(client *Client, fromStoryId int32, limit int32) (*Stories, error) {
	return client.GetChatArchivedStories(c.Id, fromStoryId, limit)
}

// GetAvailableMessageSenders is a helper method for Client.GetChatAvailableMessageSenders
func (c *Chat) GetAvailableMessageSenders(client *Client) (*ChatMessageSenders, error) {
	return client.GetChatAvailableMessageSenders(c.Id)
}

// GetAvailablePaidMessageReactionSenders is a helper method for Client.GetChatAvailablePaidMessageReactionSenders
func (c *Chat) GetAvailablePaidMessageReactionSenders(client *Client) (*MessageSenders, error) {
	return client.GetChatAvailablePaidMessageReactionSenders(c.Id)
}

// GetBoostLink is a helper method for Client.GetChatBoostLink
func (c *Chat) GetBoostLink(client *Client) (*ChatBoostLink, error) {
	return client.GetChatBoostLink(c.Id)
}

// GetBoosts is a helper method for Client.GetChatBoosts
func (c *Chat) GetBoosts(client *Client, limit int32, offset string, onlyGiftCodes bool) (*FoundChatBoosts, error) {
	return client.GetChatBoosts(c.Id, limit, offset, onlyGiftCodes)
}

// GetBoostStatus is a helper method for Client.GetChatBoostStatus
func (c *Chat) GetBoostStatus(client *Client) (*ChatBoostStatus, error) {
	return client.GetChatBoostStatus(c.Id)
}

// GetEventLog is a helper method for Client.GetChatEventLog
func (c *Chat) GetEventLog(client *Client, fromEventId int64, limit int32, query string, userIds []int64, opts *GetChatEventLogOpts) (*ChatEvents, error) {
	return client.GetChatEventLog(c.Id, fromEventId, limit, query, userIds, opts)
}

// GetHistory is a helper method for Client.GetChatHistory
func (c *Chat) GetHistory(client *Client, fromMessageId int64, limit int32, offset int32, onlyLocal bool) (*Messages, error) {
	return client.GetChatHistory(c.Id, fromMessageId, limit, offset, onlyLocal)
}

// GetInviteLink is a helper method for Client.GetChatInviteLink
func (c *Chat) GetInviteLink(client *Client, inviteLink string) (*ChatInviteLink, error) {
	return client.GetChatInviteLink(c.Id, inviteLink)
}

// GetInviteLinkCounts is a helper method for Client.GetChatInviteLinkCounts
func (c *Chat) GetInviteLinkCounts(client *Client) (*ChatInviteLinkCounts, error) {
	return client.GetChatInviteLinkCounts(c.Id)
}

// GetInviteLinkMembers is a helper method for Client.GetChatInviteLinkMembers
func (c *Chat) GetInviteLinkMembers(client *Client, inviteLink string, limit int32, onlyWithExpiredSubscription bool, opts *GetChatInviteLinkMembersOpts) (*ChatInviteLinkMembers, error) {
	return client.GetChatInviteLinkMembers(c.Id, inviteLink, limit, onlyWithExpiredSubscription, opts)
}

// GetInviteLinks is a helper method for Client.GetChatInviteLinks
func (c *Chat) GetInviteLinks(client *Client, creatorUserId int64, isRevoked bool, limit int32, offsetDate int32, offsetInviteLink string) (*ChatInviteLinks, error) {
	return client.GetChatInviteLinks(c.Id, creatorUserId, isRevoked, limit, offsetDate, offsetInviteLink)
}

// GetJoinRequests is a helper method for Client.GetChatJoinRequests
func (c *Chat) GetJoinRequests(client *Client, inviteLink string, limit int32, query string, opts *GetChatJoinRequestsOpts) (*ChatJoinRequests, error) {
	return client.GetChatJoinRequests(c.Id, inviteLink, limit, query, opts)
}

// GetListsToAddChat is a helper method for Client.GetChatListsToAddChat
func (c *Chat) GetListsToAddChat(client *Client) (*ChatLists, error) {
	return client.GetChatListsToAddChat(c.Id)
}

// GetMember is a helper method for Client.GetChatMember
func (c *Chat) GetMember(client *Client, memberId MessageSender) (*ChatMember, error) {
	return client.GetChatMember(c.Id, memberId)
}

// GetMessageByDate is a helper method for Client.GetChatMessageByDate
func (c *Chat) GetMessageByDate(client *Client, date int32) (*Message, error) {
	return client.GetChatMessageByDate(c.Id, date)
}

// GetMessageCalendar is a helper method for Client.GetChatMessageCalendar
func (c *Chat) GetMessageCalendar(client *Client, filter SearchMessagesFilter, fromMessageId int64, opts *GetChatMessageCalendarOpts) (*MessageCalendar, error) {
	return client.GetChatMessageCalendar(c.Id, filter, fromMessageId, opts)
}

// GetMessageCount is a helper method for Client.GetChatMessageCount
func (c *Chat) GetMessageCount(client *Client, filter SearchMessagesFilter, returnLocal bool, opts *GetChatMessageCountOpts) (*Count, error) {
	return client.GetChatMessageCount(c.Id, filter, returnLocal, opts)
}

// GetMessagePosition is a helper method for Client.GetChatMessagePosition
func (c *Chat) GetMessagePosition(client *Client, filter SearchMessagesFilter, messageId int64, opts *GetChatMessagePositionOpts) (*Count, error) {
	return client.GetChatMessagePosition(c.Id, filter, messageId, opts)
}

// GetOwnerAfterLeaving is a helper method for Client.GetChatOwnerAfterLeaving
func (c *Chat) GetOwnerAfterLeaving(client *Client) (*User, error) {
	return client.GetChatOwnerAfterLeaving(c.Id)
}

// GetPinnedMessage is a helper method for Client.GetChatPinnedMessage
func (c *Chat) GetPinnedMessage(client *Client) (*Message, error) {
	return client.GetChatPinnedMessage(c.Id)
}

// GetPostedToChatPageStories is a helper method for Client.GetChatPostedToChatPageStories
func (c *Chat) GetPostedToChatPageStories(client *Client, fromStoryId int32, limit int32) (*Stories, error) {
	return client.GetChatPostedToChatPageStories(c.Id, fromStoryId, limit)
}

// GetRevenueStatistics is a helper method for Client.GetChatRevenueStatistics
func (c *Chat) GetRevenueStatistics(client *Client, isDark bool) (*ChatRevenueStatistics, error) {
	return client.GetChatRevenueStatistics(c.Id, isDark)
}

// GetRevenueTransactions is a helper method for Client.GetChatRevenueTransactions
func (c *Chat) GetRevenueTransactions(client *Client, limit int32, offset string) (*ChatRevenueTransactions, error) {
	return client.GetChatRevenueTransactions(c.Id, limit, offset)
}

// GetRevenueWithdrawalUrl is a helper method for Client.GetChatRevenueWithdrawalUrl
func (c *Chat) GetRevenueWithdrawalUrl(client *Client, password string) (*HttpUrl, error) {
	return client.GetChatRevenueWithdrawalUrl(c.Id, password)
}

// GetScheduledMessages is a helper method for Client.GetChatScheduledMessages
func (c *Chat) GetScheduledMessages(client *Client) (*Messages, error) {
	return client.GetChatScheduledMessages(c.Id)
}

// GetSimilarChatCount is a helper method for Client.GetChatSimilarChatCount
func (c *Chat) GetSimilarChatCount(client *Client, returnLocal bool) (*Count, error) {
	return client.GetChatSimilarChatCount(c.Id, returnLocal)
}

// GetSimilarChats is a helper method for Client.GetChatSimilarChats
func (c *Chat) GetSimilarChats(client *Client) (*Chats, error) {
	return client.GetChatSimilarChats(c.Id)
}

// GetSparseMessagePositions is a helper method for Client.GetChatSparseMessagePositions
func (c *Chat) GetSparseMessagePositions(client *Client, filter SearchMessagesFilter, fromMessageId int64, limit int32, savedMessagesTopicId int64) (*MessagePositions, error) {
	return client.GetChatSparseMessagePositions(c.Id, filter, fromMessageId, limit, savedMessagesTopicId)
}

// GetSponsoredMessages is a helper method for Client.GetChatSponsoredMessages
func (c *Chat) GetSponsoredMessages(client *Client) (*SponsoredMessages, error) {
	return client.GetChatSponsoredMessages(c.Id)
}

// GetStatistics is a helper method for Client.GetChatStatistics
func (c *Chat) GetStatistics(client *Client, isDark bool) (ChatStatistics, error) {
	return client.GetChatStatistics(c.Id, isDark)
}

// GetStoryAlbums is a helper method for Client.GetChatStoryAlbums
func (c *Chat) GetStoryAlbums(client *Client) (*StoryAlbums, error) {
	return client.GetChatStoryAlbums(c.Id)
}

// GetDirectMessagesTopic is a helper method for Client.GetDirectMessagesChatTopic
func (c *Chat) GetDirectMessagesTopic(client *Client, topicId int64) (*DirectMessagesChatTopic, error) {
	return client.GetDirectMessagesChatTopic(c.Id, topicId)
}

// GetDirectMessagesTopicHistory is a helper method for Client.GetDirectMessagesChatTopicHistory
func (c *Chat) GetDirectMessagesTopicHistory(client *Client, fromMessageId int64, limit int32, offset int32, topicId int64) (*Messages, error) {
	return client.GetDirectMessagesChatTopicHistory(c.Id, fromMessageId, limit, offset, topicId)
}

// GetDirectMessagesTopicMessageByDate is a helper method for Client.GetDirectMessagesChatTopicMessageByDate
func (c *Chat) GetDirectMessagesTopicMessageByDate(client *Client, date int32, topicId int64) (*Message, error) {
	return client.GetDirectMessagesChatTopicMessageByDate(c.Id, date, topicId)
}

// GetDirectMessagesTopicRevenue is a helper method for Client.GetDirectMessagesChatTopicRevenue
func (c *Chat) GetDirectMessagesTopicRevenue(client *Client, topicId int64) (*StarCount, error) {
	return client.GetDirectMessagesChatTopicRevenue(c.Id, topicId)
}

// GetForumTopic is a helper method for Client.GetForumTopic
func (c *Chat) GetForumTopic(client *Client, forumTopicId int32) (*ForumTopic, error) {
	return client.GetForumTopic(c.Id, forumTopicId)
}

// GetForumTopicHistory is a helper method for Client.GetForumTopicHistory
func (c *Chat) GetForumTopicHistory(client *Client, forumTopicId int32, fromMessageId int64, limit int32, offset int32) (*Messages, error) {
	return client.GetForumTopicHistory(c.Id, forumTopicId, fromMessageId, limit, offset)
}

// GetForumTopicLink is a helper method for Client.GetForumTopicLink
func (c *Chat) GetForumTopicLink(client *Client, forumTopicId int32) (*MessageLink, error) {
	return client.GetForumTopicLink(c.Id, forumTopicId)
}

// GetForumTopics is a helper method for Client.GetForumTopics
func (c *Chat) GetForumTopics(client *Client, limit int32, offsetDate int32, offsetForumTopicId int32, offsetMessageId int64, query string) (*ForumTopics, error) {
	return client.GetForumTopics(c.Id, limit, offsetDate, offsetForumTopicId, offsetMessageId, query)
}

// GetGameHighScores is a helper method for Client.GetGameHighScores
func (c *Chat) GetGameHighScores(client *Client, messageId int64, userId int64) (*GameHighScores, error) {
	return client.GetGameHighScores(c.Id, messageId, userId)
}

// GetGiveawayInfo is a helper method for Client.GetGiveawayInfo
func (c *Chat) GetGiveawayInfo(client *Client, messageId int64) (GiveawayInfo, error) {
	return client.GetGiveawayInfo(c.Id, messageId)
}

// GetInlineQueryResults is a helper method for Client.GetInlineQueryResults
func (c *Chat) GetInlineQueryResults(client *Client, botUserId int64, offset string, query string, opts *GetInlineQueryResultsOpts) (*InlineQueryResults, error) {
	return client.GetInlineQueryResults(botUserId, c.Id, offset, query, opts)
}

// GetLiveStoryRtmpUrl is a helper method for Client.GetLiveStoryRtmpUrl
func (c *Chat) GetLiveStoryRtmpUrl(client *Client) (*RtmpUrl, error) {
	return client.GetLiveStoryRtmpUrl(c.Id)
}

// GetLoginUrl is a helper method for Client.GetLoginUrl
func (c *Chat) GetLoginUrl(client *Client, allowWriteAccess bool, buttonId int64, messageId int64) (*HttpUrl, error) {
	return client.GetLoginUrl(allowWriteAccess, buttonId, c.Id, messageId)
}

// GetLoginUrlInfo is a helper method for Client.GetLoginUrlInfo
func (c *Chat) GetLoginUrlInfo(client *Client, buttonId int64, messageId int64) (LoginUrlInfo, error) {
	return client.GetLoginUrlInfo(buttonId, c.Id, messageId)
}

// GetMainWebApp is a helper method for Client.GetMainWebApp
func (c *Chat) GetMainWebApp(client *Client, botUserId int64, parameters *WebAppOpenParameters, startParameter string) (*MainWebApp, error) {
	return client.GetMainWebApp(botUserId, c.Id, parameters, startParameter)
}

// GetMapThumbnailFile is a helper method for Client.GetMapThumbnailFile
func (c *Chat) GetMapThumbnailFile(client *Client, height int32, location *Location, scale int32, width int32, zoom int32) (*File, error) {
	return client.GetMapThumbnailFile(c.Id, height, location, scale, width, zoom)
}

// GetMessage is a helper method for Client.GetMessage
func (c *Chat) GetMessage(client *Client, messageId int64) (*Message, error) {
	return client.GetMessage(c.Id, messageId)
}

// GetMessageAddedReactions is a helper method for Client.GetMessageAddedReactions
func (c *Chat) GetMessageAddedReactions(client *Client, limit int32, messageId int64, offset string, opts *GetMessageAddedReactionsOpts) (*AddedReactions, error) {
	return client.GetMessageAddedReactions(c.Id, limit, messageId, offset, opts)
}

// GetMessageAuthor is a helper method for Client.GetMessageAuthor
func (c *Chat) GetMessageAuthor(client *Client, messageId int64) (*User, error) {
	return client.GetMessageAuthor(c.Id, messageId)
}

// GetMessageAvailableReactions is a helper method for Client.GetMessageAvailableReactions
func (c *Chat) GetMessageAvailableReactions(client *Client, messageId int64, rowSize int32) (*AvailableReactions, error) {
	return client.GetMessageAvailableReactions(c.Id, messageId, rowSize)
}

// GetMessageEmbeddingCode is a helper method for Client.GetMessageEmbeddingCode
func (c *Chat) GetMessageEmbeddingCode(client *Client, forAlbum bool, messageId int64) (*Text, error) {
	return client.GetMessageEmbeddingCode(c.Id, forAlbum, messageId)
}

// GetMessageImportConfirmationText is a helper method for Client.GetMessageImportConfirmationText
func (c *Chat) GetMessageImportConfirmationText(client *Client) (*Text, error) {
	return client.GetMessageImportConfirmationText(c.Id)
}

// GetMessageLink is a helper method for Client.GetMessageLink
func (c *Chat) GetMessageLink(client *Client, forAlbum bool, inMessageThread bool, mediaTimestamp int32, messageId int64) (*MessageLink, error) {
	return client.GetMessageLink(c.Id, forAlbum, inMessageThread, mediaTimestamp, messageId)
}

// GetMessageLocally is a helper method for Client.GetMessageLocally
func (c *Chat) GetMessageLocally(client *Client, messageId int64) (*Message, error) {
	return client.GetMessageLocally(c.Id, messageId)
}

// GetMessageProperties is a helper method for Client.GetMessageProperties
func (c *Chat) GetMessageProperties(client *Client, messageId int64) (*MessageProperties, error) {
	return client.GetMessageProperties(c.Id, messageId)
}

// GetMessagePublicForwards is a helper method for Client.GetMessagePublicForwards
func (c *Chat) GetMessagePublicForwards(client *Client, limit int32, messageId int64, offset string) (*PublicForwards, error) {
	return client.GetMessagePublicForwards(c.Id, limit, messageId, offset)
}

// GetMessageReadDate is a helper method for Client.GetMessageReadDate
func (c *Chat) GetMessageReadDate(client *Client, messageId int64) (MessageReadDate, error) {
	return client.GetMessageReadDate(c.Id, messageId)
}

// GetMessages is a helper method for Client.GetMessages
func (c *Chat) GetMessages(client *Client, messageIds []int64) (*Messages, error) {
	return client.GetMessages(c.Id, messageIds)
}

// GetMessageStatistics is a helper method for Client.GetMessageStatistics
func (c *Chat) GetMessageStatistics(client *Client, isDark bool, messageId int64) (*MessageStatistics, error) {
	return client.GetMessageStatistics(c.Id, isDark, messageId)
}

// GetMessageThread is a helper method for Client.GetMessageThread
func (c *Chat) GetMessageThread(client *Client, messageId int64) (*MessageThreadInfo, error) {
	return client.GetMessageThread(c.Id, messageId)
}

// GetMessageThreadHistory is a helper method for Client.GetMessageThreadHistory
func (c *Chat) GetMessageThreadHistory(client *Client, fromMessageId int64, limit int32, messageId int64, offset int32) (*Messages, error) {
	return client.GetMessageThreadHistory(c.Id, fromMessageId, limit, messageId, offset)
}

// GetMessageViewers is a helper method for Client.GetMessageViewers
func (c *Chat) GetMessageViewers(client *Client, messageId int64) (*MessageViewers, error) {
	return client.GetMessageViewers(c.Id, messageId)
}

// GetPaymentReceipt is a helper method for Client.GetPaymentReceipt
func (c *Chat) GetPaymentReceipt(client *Client, messageId int64) (*PaymentReceipt, error) {
	return client.GetPaymentReceipt(c.Id, messageId)
}

// GetPollVoters is a helper method for Client.GetPollVoters
func (c *Chat) GetPollVoters(client *Client, limit int32, messageId int64, offset int32, optionId int32) (*MessageSenders, error) {
	return client.GetPollVoters(c.Id, limit, messageId, offset, optionId)
}

// GetRepliedMessage is a helper method for Client.GetRepliedMessage
func (c *Chat) GetRepliedMessage(client *Client, messageId int64) (*Message, error) {
	return client.GetRepliedMessage(c.Id, messageId)
}

// GetStatisticalGraph is a helper method for Client.GetStatisticalGraph
func (c *Chat) GetStatisticalGraph(client *Client, token string, x int64) (StatisticalGraph, error) {
	return client.GetStatisticalGraph(c.Id, token, x)
}

// GetStickers is a helper method for Client.GetStickers
func (c *Chat) GetStickers(client *Client, limit int32, query string, stickerType StickerType) (*Stickers, error) {
	return client.GetStickers(c.Id, limit, query, stickerType)
}

// GetStoryAlbumStories is a helper method for Client.GetStoryAlbumStories
func (c *Chat) GetStoryAlbumStories(client *Client, limit int32, offset int32, storyAlbumId int32) (*Stories, error) {
	return client.GetStoryAlbumStories(c.Id, limit, offset, storyAlbumId)
}

// GetStoryStatistics is a helper method for Client.GetStoryStatistics
func (c *Chat) GetStoryStatistics(client *Client, isDark bool, storyId int32) (*StoryStatistics, error) {
	return client.GetStoryStatistics(c.Id, isDark, storyId)
}

// GetUserBoosts is a helper method for Client.GetUserChatBoosts
func (c *Chat) GetUserBoosts(client *Client, userId int64) (*FoundChatBoosts, error) {
	return client.GetUserChatBoosts(c.Id, userId)
}

// GetVideoAvailableParticipants is a helper method for Client.GetVideoChatAvailableParticipants
func (c *Chat) GetVideoAvailableParticipants(client *Client) (*MessageSenders, error) {
	return client.GetVideoChatAvailableParticipants(c.Id)
}

// GetVideoRtmpUrl is a helper method for Client.GetVideoChatRtmpUrl
func (c *Chat) GetVideoRtmpUrl(client *Client) (*RtmpUrl, error) {
	return client.GetVideoChatRtmpUrl(c.Id)
}

// GetVideoMessageAdvertisements is a helper method for Client.GetVideoMessageAdvertisements
func (c *Chat) GetVideoMessageAdvertisements(client *Client, messageId int64) (*VideoMessageAdvertisements, error) {
	return client.GetVideoMessageAdvertisements(c.Id, messageId)
}

// GetWebAppLinkUrl is a helper method for Client.GetWebAppLinkUrl
func (c *Chat) GetWebAppLinkUrl(client *Client, allowWriteAccess bool, botUserId int64, parameters *WebAppOpenParameters, startParameter string, webAppShortName string) (*HttpUrl, error) {
	return client.GetWebAppLinkUrl(allowWriteAccess, botUserId, c.Id, parameters, startParameter, webAppShortName)
}

// ImportMessages is a helper method for Client.ImportMessages
func (c *Chat) ImportMessages(client *Client, attachedFiles []InputFile, messageFile InputFile) error {
	return client.ImportMessages(attachedFiles, c.Id, messageFile)
}

// Join is a helper method for Client.JoinChat
func (c *Chat) Join(client *Client) error {
	return client.JoinChat(c.Id)
}

// Leave is a helper method for Client.LeaveChat
func (c *Chat) Leave(client *Client) error {
	return client.LeaveChat(c.Id)
}

// LoadDirectMessagesTopics is a helper method for Client.LoadDirectMessagesChatTopics
func (c *Chat) LoadDirectMessagesTopics(client *Client, limit int32) error {
	return client.LoadDirectMessagesChatTopics(c.Id, limit)
}

// MarkChecklistTasksAsDone is a helper method for Client.MarkChecklistTasksAsDone
func (c *Chat) MarkChecklistTasksAsDone(client *Client, markedAsDoneTaskIds []int32, markedAsNotDoneTaskIds []int32, messageId int64) error {
	return client.MarkChecklistTasksAsDone(c.Id, markedAsDoneTaskIds, markedAsNotDoneTaskIds, messageId)
}

// Open is a helper method for Client.OpenChat
func (c *Chat) Open(client *Client) error {
	return client.OpenChat(c.Id)
}

// OpenSimilarChat is a helper method for Client.OpenChatSimilarChat
func (c *Chat) OpenSimilarChat(client *Client, openedChatId int64) error {
	return client.OpenChatSimilarChat(c.Id, openedChatId)
}

// OpenMessageContent is a helper method for Client.OpenMessageContent
func (c *Chat) OpenMessageContent(client *Client, messageId int64) error {
	return client.OpenMessageContent(c.Id, messageId)
}

// OpenWebApp is a helper method for Client.OpenWebApp
func (c *Chat) OpenWebApp(client *Client, botUserId int64, parameters *WebAppOpenParameters, url string, opts *OpenWebAppOpts) (*WebAppInfo, error) {
	return client.OpenWebApp(botUserId, c.Id, parameters, url, opts)
}

// PinMessage is a helper method for Client.PinChatMessage
func (c *Chat) PinMessage(client *Client, disableNotification bool, messageId int64, onlyForSelf bool) error {
	return client.PinChatMessage(c.Id, disableNotification, messageId, onlyForSelf)
}

// PostStory is a helper method for Client.PostStory
func (c *Chat) PostStory(client *Client, activePeriod int32, albumIds []int32, content InputStoryContent, isPostedToChatPage bool, privacySettings StoryPrivacySettings, protectContent bool, opts *PostStoryOpts) (*Story, error) {
	return client.PostStory(activePeriod, albumIds, c.Id, content, isPostedToChatPage, privacySettings, protectContent, opts)
}

// ProcessJoinRequest is a helper method for Client.ProcessChatJoinRequest
func (c *Chat) ProcessJoinRequest(client *Client, approve bool, userId int64) error {
	return client.ProcessChatJoinRequest(approve, c.Id, userId)
}

// ProcessJoinRequests is a helper method for Client.ProcessChatJoinRequests
func (c *Chat) ProcessJoinRequests(client *Client, approve bool, inviteLink string) error {
	return client.ProcessChatJoinRequests(approve, c.Id, inviteLink)
}

// RateSpeechRecognition is a helper method for Client.RateSpeechRecognition
func (c *Chat) RateSpeechRecognition(client *Client, isGood bool, messageId int64) error {
	return client.RateSpeechRecognition(c.Id, isGood, messageId)
}

// ReadAllMentions is a helper method for Client.ReadAllChatMentions
func (c *Chat) ReadAllMentions(client *Client) error {
	return client.ReadAllChatMentions(c.Id)
}

// ReadAllReactions is a helper method for Client.ReadAllChatReactions
func (c *Chat) ReadAllReactions(client *Client) error {
	return client.ReadAllChatReactions(c.Id)
}

// ReadAllDirectMessagesTopicReactions is a helper method for Client.ReadAllDirectMessagesChatTopicReactions
func (c *Chat) ReadAllDirectMessagesTopicReactions(client *Client, topicId int64) error {
	return client.ReadAllDirectMessagesChatTopicReactions(c.Id, topicId)
}

// ReadAllForumTopicMentions is a helper method for Client.ReadAllForumTopicMentions
func (c *Chat) ReadAllForumTopicMentions(client *Client, forumTopicId int32) error {
	return client.ReadAllForumTopicMentions(c.Id, forumTopicId)
}

// ReadAllForumTopicReactions is a helper method for Client.ReadAllForumTopicReactions
func (c *Chat) ReadAllForumTopicReactions(client *Client, forumTopicId int32) error {
	return client.ReadAllForumTopicReactions(c.Id, forumTopicId)
}

// ReadBusinessMessage is a helper method for Client.ReadBusinessMessage
func (c *Chat) ReadBusinessMessage(client *Client, businessConnectionId string, messageId int64) error {
	return client.ReadBusinessMessage(businessConnectionId, c.Id, messageId)
}

// RecognizeSpeech is a helper method for Client.RecognizeSpeech
func (c *Chat) RecognizeSpeech(client *Client, messageId int64) error {
	return client.RecognizeSpeech(c.Id, messageId)
}

// RemoveBusinessConnectedBotFrom is a helper method for Client.RemoveBusinessConnectedBotFromChat
func (c *Chat) RemoveBusinessConnectedBotFrom(client *Client) error {
	return client.RemoveBusinessConnectedBotFromChat(c.Id)
}

// RemoveActionBar is a helper method for Client.RemoveChatActionBar
func (c *Chat) RemoveActionBar(client *Client) error {
	return client.RemoveChatActionBar(c.Id)
}

// RemoveMessageReaction is a helper method for Client.RemoveMessageReaction
func (c *Chat) RemoveMessageReaction(client *Client, messageId int64, reactionType ReactionType) error {
	return client.RemoveMessageReaction(c.Id, messageId, reactionType)
}

// RemovePendingPaidMessageReactions is a helper method for Client.RemovePendingPaidMessageReactions
func (c *Chat) RemovePendingPaidMessageReactions(client *Client, messageId int64) error {
	return client.RemovePendingPaidMessageReactions(c.Id, messageId)
}

// RemoveRecentlyFound is a helper method for Client.RemoveRecentlyFoundChat
func (c *Chat) RemoveRecentlyFound(client *Client) error {
	return client.RemoveRecentlyFoundChat(c.Id)
}

// RemoveStoryAlbumStories is a helper method for Client.RemoveStoryAlbumStories
func (c *Chat) RemoveStoryAlbumStories(client *Client, storyAlbumId int32, storyIds []int32) (*StoryAlbum, error) {
	return client.RemoveStoryAlbumStories(c.Id, storyAlbumId, storyIds)
}

// RemoveTop is a helper method for Client.RemoveTopChat
func (c *Chat) RemoveTop(client *Client, category TopChatCategory) error {
	return client.RemoveTopChat(category, c.Id)
}

// ReorderStoryAlbums is a helper method for Client.ReorderStoryAlbums
func (c *Chat) ReorderStoryAlbums(client *Client, storyAlbumIds []int32) error {
	return client.ReorderStoryAlbums(c.Id, storyAlbumIds)
}

// ReorderStoryAlbumStories is a helper method for Client.ReorderStoryAlbumStories
func (c *Chat) ReorderStoryAlbumStories(client *Client, storyAlbumId int32, storyIds []int32) (*StoryAlbum, error) {
	return client.ReorderStoryAlbumStories(c.Id, storyAlbumId, storyIds)
}

// ReplaceLiveStoryRtmpUrl is a helper method for Client.ReplaceLiveStoryRtmpUrl
func (c *Chat) ReplaceLiveStoryRtmpUrl(client *Client) (*RtmpUrl, error) {
	return client.ReplaceLiveStoryRtmpUrl(c.Id)
}

// ReplacePrimaryInviteLink is a helper method for Client.ReplacePrimaryChatInviteLink
func (c *Chat) ReplacePrimaryInviteLink(client *Client) (*ChatInviteLink, error) {
	return client.ReplacePrimaryChatInviteLink(c.Id)
}

// ReplaceVideoRtmpUrl is a helper method for Client.ReplaceVideoChatRtmpUrl
func (c *Chat) ReplaceVideoRtmpUrl(client *Client) (*RtmpUrl, error) {
	return client.ReplaceVideoChatRtmpUrl(c.Id)
}

// Report is a helper method for Client.ReportChat
func (c *Chat) Report(client *Client, messageIds []int64, optionId []byte, text string) (ReportChatResult, error) {
	return client.ReportChat(c.Id, messageIds, optionId, text)
}

// ReportPhoto is a helper method for Client.ReportChatPhoto
func (c *Chat) ReportPhoto(client *Client, fileId int32, reason ReportReason, text string) error {
	return client.ReportChatPhoto(c.Id, fileId, reason, text)
}

// ReportSponsoredMessage is a helper method for Client.ReportChatSponsoredMessage
func (c *Chat) ReportSponsoredMessage(client *Client, messageId int64, optionId []byte) (ReportSponsoredResult, error) {
	return client.ReportChatSponsoredMessage(c.Id, messageId, optionId)
}

// ReportMessageReactions is a helper method for Client.ReportMessageReactions
func (c *Chat) ReportMessageReactions(client *Client, messageId int64, senderId MessageSender) error {
	return client.ReportMessageReactions(c.Id, messageId, senderId)
}

// ResendMessages is a helper method for Client.ResendMessages
func (c *Chat) ResendMessages(client *Client, messageIds []int64, paidMessageStarCount int64, opts *ResendMessagesOpts) (*Messages, error) {
	return client.ResendMessages(c.Id, messageIds, paidMessageStarCount, opts)
}

// RevokeInviteLink is a helper method for Client.RevokeChatInviteLink
func (c *Chat) RevokeInviteLink(client *Client, inviteLink string) (*ChatInviteLinks, error) {
	return client.RevokeChatInviteLink(c.Id, inviteLink)
}

// SaveApplicationLogEvent is a helper method for Client.SaveApplicationLogEvent
func (c *Chat) SaveApplicationLogEvent(client *Client, data JsonValue, typeField string) error {
	return client.SaveApplicationLogEvent(c.Id, data, typeField)
}

// SearchMembers is a helper method for Client.SearchChatMembers
func (c *Chat) SearchMembers(client *Client, limit int32, query string, opts *SearchChatMembersOpts) (*ChatMembers, error) {
	return client.SearchChatMembers(c.Id, limit, query, opts)
}

// SearchMessages is a helper method for Client.SearchChatMessages
func (c *Chat) SearchMessages(client *Client, fromMessageId int64, limit int32, offset int32, query string, opts *SearchChatMessagesOpts) (*FoundChatMessages, error) {
	return client.SearchChatMessages(c.Id, fromMessageId, limit, offset, query, opts)
}

// SearchRecentLocationMessages is a helper method for Client.SearchChatRecentLocationMessages
func (c *Chat) SearchRecentLocationMessages(client *Client, limit int32) (*Messages, error) {
	return client.SearchChatRecentLocationMessages(c.Id, limit)
}

// SearchSecretMessages is a helper method for Client.SearchSecretMessages
func (c *Chat) SearchSecretMessages(client *Client, limit int32, offset string, query string, opts *SearchSecretMessagesOpts) (*FoundMessages, error) {
	return client.SearchSecretMessages(c.Id, limit, offset, query, opts)
}

// SendBotStartMessage is a helper method for Client.SendBotStartMessage
func (c *Chat) SendBotStartMessage(client *Client, botUserId int64, parameter string) (*Message, error) {
	return client.SendBotStartMessage(botUserId, c.Id, parameter)
}

// SendBusinessMessage is a helper method for Client.SendBusinessMessage
func (c *Chat) SendBusinessMessage(client *Client, businessConnectionId string, disableNotification bool, effectId int64, inputMessageContent InputMessageContent, protectContent bool, opts *SendBusinessMessageOpts) (*BusinessMessage, error) {
	return client.SendBusinessMessage(businessConnectionId, c.Id, disableNotification, effectId, inputMessageContent, protectContent, opts)
}

// SendBusinessMessageAlbum is a helper method for Client.SendBusinessMessageAlbum
func (c *Chat) SendBusinessMessageAlbum(client *Client, businessConnectionId string, disableNotification bool, effectId int64, inputMessageContents []InputMessageContent, protectContent bool, opts *SendBusinessMessageAlbumOpts) (*BusinessMessages, error) {
	return client.SendBusinessMessageAlbum(businessConnectionId, c.Id, disableNotification, effectId, inputMessageContents, protectContent, opts)
}

// SendAction is a helper method for Client.SendChatAction
func (c *Chat) SendAction(client *Client, businessConnectionId string, opts *SendChatActionOpts) error {
	return client.SendChatAction(businessConnectionId, c.Id, opts)
}

// SendInlineQueryResultMessage is a helper method for Client.SendInlineQueryResultMessage
func (c *Chat) SendInlineQueryResultMessage(client *Client, hideViaBot bool, queryId int64, resultId string, opts *SendInlineQueryResultMessageOpts) (*Message, error) {
	return client.SendInlineQueryResultMessage(c.Id, hideViaBot, queryId, resultId, opts)
}

// SendMessage is a helper method for Client.SendMessage
func (c *Chat) SendMessage(client *Client, inputMessageContent InputMessageContent, opts *SendMessageOpts) (*Message, error) {
	return client.SendMessage(c.Id, inputMessageContent, opts)
}

// SendMessageAlbum is a helper method for Client.SendMessageAlbum
func (c *Chat) SendMessageAlbum(client *Client, inputMessageContents []InputMessageContent, opts *SendMessageAlbumOpts) (*Messages, error) {
	return client.SendMessageAlbum(c.Id, inputMessageContents, opts)
}

// SendQuickReplyShortcutMessages is a helper method for Client.SendQuickReplyShortcutMessages
func (c *Chat) SendQuickReplyShortcutMessages(client *Client, sendingId int32, shortcutId int32) (*Messages, error) {
	return client.SendQuickReplyShortcutMessages(c.Id, sendingId, shortcutId)
}

// SendTextMessageDraft is a helper method for Client.SendTextMessageDraft
func (c *Chat) SendTextMessageDraft(client *Client, draftId int64, forumTopicId int32, text *FormattedText) error {
	return client.SendTextMessageDraft(c.Id, draftId, forumTopicId, text)
}

// SetBusinessMessageIsPinned is a helper method for Client.SetBusinessMessageIsPinned
func (c *Chat) SetBusinessMessageIsPinned(client *Client, businessConnectionId string, isPinned bool, messageId int64) error {
	return client.SetBusinessMessageIsPinned(businessConnectionId, c.Id, isPinned, messageId)
}

// SetAccentColor is a helper method for Client.SetChatAccentColor
func (c *Chat) SetAccentColor(client *Client) error {
	return client.SetChatAccentColor(c.AccentColorId, c.BackgroundCustomEmojiId, c.Id)
}

// SetActiveStoriesList is a helper method for Client.SetChatActiveStoriesList
func (c *Chat) SetActiveStoriesList(client *Client, storyList StoryList) error {
	return client.SetChatActiveStoriesList(c.Id, storyList)
}

// SetAffiliateProgram is a helper method for Client.SetChatAffiliateProgram
func (c *Chat) SetAffiliateProgram(client *Client, opts *SetChatAffiliateProgramOpts) error {
	return client.SetChatAffiliateProgram(c.Id, opts)
}

// SetAvailableReactions is a helper method for Client.SetChatAvailableReactions
func (c *Chat) SetAvailableReactions(client *Client) error {
	return client.SetChatAvailableReactions(c.AvailableReactions, c.Id)
}

// SetBackground is a helper method for Client.SetChatBackground
func (c *Chat) SetBackground(client *Client, darkThemeDimming int32, onlyForSelf bool, opts *SetChatBackgroundOpts) error {
	return client.SetChatBackground(c.Id, darkThemeDimming, onlyForSelf, opts)
}

// SetClientData is a helper method for Client.SetChatClientData
func (c *Chat) SetClientData(client *Client) error {
	return client.SetChatClientData(c.Id, c.ClientData)
}

// SetDescription is a helper method for Client.SetChatDescription
func (c *Chat) SetDescription(client *Client, description string) error {
	return client.SetChatDescription(c.Id, description)
}

// SetDirectMessagesGroup is a helper method for Client.SetChatDirectMessagesGroup
func (c *Chat) SetDirectMessagesGroup(client *Client, isEnabled bool, paidMessageStarCount int64) error {
	return client.SetChatDirectMessagesGroup(c.Id, isEnabled, paidMessageStarCount)
}

// SetDiscussionGroup is a helper method for Client.SetChatDiscussionGroup
func (c *Chat) SetDiscussionGroup(client *Client, discussionChatId int64) error {
	return client.SetChatDiscussionGroup(c.Id, discussionChatId)
}

// SetDraftMessage is a helper method for Client.SetChatDraftMessage
func (c *Chat) SetDraftMessage(client *Client, opts *SetChatDraftMessageOpts) error {
	return client.SetChatDraftMessage(c.Id, opts)
}

// SetEmojiStatus is a helper method for Client.SetChatEmojiStatus
func (c *Chat) SetEmojiStatus(client *Client, opts *SetChatEmojiStatusOpts) error {
	return client.SetChatEmojiStatus(c.Id, opts)
}

// SetLocation is a helper method for Client.SetChatLocation
func (c *Chat) SetLocation(client *Client, location *ChatLocation) error {
	return client.SetChatLocation(c.Id, location)
}

// SetMemberStatus is a helper method for Client.SetChatMemberStatus
func (c *Chat) SetMemberStatus(client *Client, memberId MessageSender, status ChatMemberStatus) error {
	return client.SetChatMemberStatus(c.Id, memberId, status)
}

// SetMessageAutoDeleteTime is a helper method for Client.SetChatMessageAutoDeleteTime
func (c *Chat) SetMessageAutoDeleteTime(client *Client) error {
	return client.SetChatMessageAutoDeleteTime(c.Id, c.MessageAutoDeleteTime)
}

// SetMessageSender is a helper method for Client.SetChatMessageSender
func (c *Chat) SetMessageSender(client *Client) error {
	return client.SetChatMessageSender(c.Id, c.MessageSenderId)
}

// SetNotificationSettings is a helper method for Client.SetChatNotificationSettings
func (c *Chat) SetNotificationSettings(client *Client) error {
	return client.SetChatNotificationSettings(c.Id, c.NotificationSettings)
}

// SetPaidMessageStarCount is a helper method for Client.SetChatPaidMessageStarCount
func (c *Chat) SetPaidMessageStarCount(client *Client, paidMessageStarCount int64) error {
	return client.SetChatPaidMessageStarCount(c.Id, paidMessageStarCount)
}

// SetPermissions is a helper method for Client.SetChatPermissions
func (c *Chat) SetPermissions(client *Client) error {
	return client.SetChatPermissions(c.Id, c.Permissions)
}

// SetPhoto is a helper method for Client.SetChatPhoto
func (c *Chat) SetPhoto(client *Client, opts *SetChatPhotoOpts) error {
	return client.SetChatPhoto(c.Id, opts)
}

// SetPinnedStories is a helper method for Client.SetChatPinnedStories
func (c *Chat) SetPinnedStories(client *Client, storyIds []int32) error {
	return client.SetChatPinnedStories(c.Id, storyIds)
}

// SetProfileAccentColor is a helper method for Client.SetChatProfileAccentColor
func (c *Chat) SetProfileAccentColor(client *Client) error {
	return client.SetChatProfileAccentColor(c.Id, c.ProfileAccentColorId, c.ProfileBackgroundCustomEmojiId)
}

// SetSlowModeDelay is a helper method for Client.SetChatSlowModeDelay
func (c *Chat) SetSlowModeDelay(client *Client, slowModeDelay int32) error {
	return client.SetChatSlowModeDelay(c.Id, slowModeDelay)
}

// SetTheme is a helper method for Client.SetChatTheme
func (c *Chat) SetTheme(client *Client, theme InputChatTheme) error {
	return client.SetChatTheme(c.Id, theme)
}

// SetTitle is a helper method for Client.SetChatTitle
func (c *Chat) SetTitle(client *Client) error {
	return client.SetChatTitle(c.Id, c.Title)
}

// SetDirectMessagesTopicIsMarkedAsUnread is a helper method for Client.SetDirectMessagesChatTopicIsMarkedAsUnread
func (c *Chat) SetDirectMessagesTopicIsMarkedAsUnread(client *Client, topicId int64) error {
	return client.SetDirectMessagesChatTopicIsMarkedAsUnread(c.Id, c.IsMarkedAsUnread, topicId)
}

// SetForumTopicNotificationSettings is a helper method for Client.SetForumTopicNotificationSettings
func (c *Chat) SetForumTopicNotificationSettings(client *Client, forumTopicId int32) error {
	return client.SetForumTopicNotificationSettings(c.Id, forumTopicId, c.NotificationSettings)
}

// SetGameScore is a helper method for Client.SetGameScore
func (c *Chat) SetGameScore(client *Client, editMessage bool, force bool, messageId int64, score int32, userId int64) (*Message, error) {
	return client.SetGameScore(c.Id, editMessage, force, messageId, score, userId)
}

// SetMessageFactCheck is a helper method for Client.SetMessageFactCheck
func (c *Chat) SetMessageFactCheck(client *Client, messageId int64, opts *SetMessageFactCheckOpts) error {
	return client.SetMessageFactCheck(c.Id, messageId, opts)
}

// SetMessageReactions is a helper method for Client.SetMessageReactions
func (c *Chat) SetMessageReactions(client *Client, isBig bool, messageId int64, reactionTypes []ReactionType) error {
	return client.SetMessageReactions(c.Id, isBig, messageId, reactionTypes)
}

// SetPaidMessageReactionType is a helper method for Client.SetPaidMessageReactionType
func (c *Chat) SetPaidMessageReactionType(client *Client, messageId int64, typeField PaidReactionType) error {
	return client.SetPaidMessageReactionType(c.Id, messageId, typeField)
}

// SetPersonal is a helper method for Client.SetPersonalChat
func (c *Chat) SetPersonal(client *Client) error {
	return client.SetPersonalChat(c.Id)
}

// SetPinnedForumTopics is a helper method for Client.SetPinnedForumTopics
func (c *Chat) SetPinnedForumTopics(client *Client, forumTopicIds []int32) error {
	return client.SetPinnedForumTopics(c.Id, forumTopicIds)
}

// SetPollAnswer is a helper method for Client.SetPollAnswer
func (c *Chat) SetPollAnswer(client *Client, messageId int64, optionIds []int32) error {
	return client.SetPollAnswer(c.Id, messageId, optionIds)
}

// SetStoryAlbumName is a helper method for Client.SetStoryAlbumName
func (c *Chat) SetStoryAlbumName(client *Client, name string, storyAlbumId int32) (*StoryAlbum, error) {
	return client.SetStoryAlbumName(c.Id, name, storyAlbumId)
}

// SetVideoDefaultParticipant is a helper method for Client.SetVideoChatDefaultParticipant
func (c *Chat) SetVideoDefaultParticipant(client *Client, defaultParticipantId MessageSender) error {
	return client.SetVideoChatDefaultParticipant(c.Id, defaultParticipantId)
}

// ShareWithBot is a helper method for Client.ShareChatWithBot
func (c *Chat) ShareWithBot(client *Client, buttonId int32, messageId int64, onlyCheck bool, sharedChatId int64) error {
	return client.ShareChatWithBot(buttonId, c.Id, messageId, onlyCheck, sharedChatId)
}

// ShareUsersWithBot is a helper method for Client.ShareUsersWithBot
func (c *Chat) ShareUsersWithBot(client *Client, buttonId int32, messageId int64, onlyCheck bool, sharedUserIds []int64) error {
	return client.ShareUsersWithBot(buttonId, c.Id, messageId, onlyCheck, sharedUserIds)
}

// StartLiveStory is a helper method for Client.StartLiveStory
func (c *Chat) StartLiveStory(client *Client, enableMessages bool, isRtmpStream bool, paidMessageStarCount int64, privacySettings StoryPrivacySettings, protectContent bool) (StartLiveStoryResult, error) {
	return client.StartLiveStory(c.Id, enableMessages, isRtmpStream, paidMessageStarCount, privacySettings, protectContent)
}

// StopBusinessPoll is a helper method for Client.StopBusinessPoll
func (c *Chat) StopBusinessPoll(client *Client, businessConnectionId string, messageId int64, opts *StopBusinessPollOpts) (*BusinessMessage, error) {
	return client.StopBusinessPoll(businessConnectionId, c.Id, messageId, opts)
}

// StopPoll is a helper method for Client.StopPoll
func (c *Chat) StopPoll(client *Client, messageId int64, opts *StopPollOpts) error {
	return client.StopPoll(c.Id, messageId, opts)
}

// SummarizeMessage is a helper method for Client.SummarizeMessage
func (c *Chat) SummarizeMessage(client *Client, messageId int64, opts *SummarizeMessageOpts) (*FormattedText, error) {
	return client.SummarizeMessage(c.Id, messageId, opts)
}

// ToggleBusinessConnectedBotIsPaused is a helper method for Client.ToggleBusinessConnectedBotChatIsPaused
func (c *Chat) ToggleBusinessConnectedBotIsPaused(client *Client, isPaused bool) error {
	return client.ToggleBusinessConnectedBotChatIsPaused(c.Id, isPaused)
}

// ToggleDefaultDisableNotification is a helper method for Client.ToggleChatDefaultDisableNotification
func (c *Chat) ToggleDefaultDisableNotification(client *Client) error {
	return client.ToggleChatDefaultDisableNotification(c.Id, c.DefaultDisableNotification)
}

// ToggleGiftNotifications is a helper method for Client.ToggleChatGiftNotifications
func (c *Chat) ToggleGiftNotifications(client *Client, areEnabled bool) error {
	return client.ToggleChatGiftNotifications(areEnabled, c.Id)
}

// ToggleHasProtectedContent is a helper method for Client.ToggleChatHasProtectedContent
func (c *Chat) ToggleHasProtectedContent(client *Client) error {
	return client.ToggleChatHasProtectedContent(c.Id, c.HasProtectedContent)
}

// ToggleIsMarkedAsUnread is a helper method for Client.ToggleChatIsMarkedAsUnread
func (c *Chat) ToggleIsMarkedAsUnread(client *Client) error {
	return client.ToggleChatIsMarkedAsUnread(c.Id, c.IsMarkedAsUnread)
}

// ToggleIsPinned is a helper method for Client.ToggleChatIsPinned
func (c *Chat) ToggleIsPinned(client *Client, chatList ChatList, isPinned bool) error {
	return client.ToggleChatIsPinned(c.Id, chatList, isPinned)
}

// ToggleIsTranslatable is a helper method for Client.ToggleChatIsTranslatable
func (c *Chat) ToggleIsTranslatable(client *Client) error {
	return client.ToggleChatIsTranslatable(c.Id, c.IsTranslatable)
}

// ToggleViewAsTopics is a helper method for Client.ToggleChatViewAsTopics
func (c *Chat) ToggleViewAsTopics(client *Client) error {
	return client.ToggleChatViewAsTopics(c.Id, c.ViewAsTopics)
}

// ToggleDirectMessagesTopicCanSendUnpaidMessages is a helper method for Client.ToggleDirectMessagesChatTopicCanSendUnpaidMessages
func (c *Chat) ToggleDirectMessagesTopicCanSendUnpaidMessages(client *Client, canSendUnpaidMessages bool, refundPayments bool, topicId int64) error {
	return client.ToggleDirectMessagesChatTopicCanSendUnpaidMessages(canSendUnpaidMessages, c.Id, refundPayments, topicId)
}

// ToggleForumTopicIsClosed is a helper method for Client.ToggleForumTopicIsClosed
func (c *Chat) ToggleForumTopicIsClosed(client *Client, forumTopicId int32, isClosed bool) error {
	return client.ToggleForumTopicIsClosed(c.Id, forumTopicId, isClosed)
}

// ToggleForumTopicIsPinned is a helper method for Client.ToggleForumTopicIsPinned
func (c *Chat) ToggleForumTopicIsPinned(client *Client, forumTopicId int32, isPinned bool) error {
	return client.ToggleForumTopicIsPinned(c.Id, forumTopicId, isPinned)
}

// ToggleGeneralForumTopicIsHidden is a helper method for Client.ToggleGeneralForumTopicIsHidden
func (c *Chat) ToggleGeneralForumTopicIsHidden(client *Client, isHidden bool) error {
	return client.ToggleGeneralForumTopicIsHidden(c.Id, isHidden)
}

// TransferOwnership is a helper method for Client.TransferChatOwnership
func (c *Chat) TransferOwnership(client *Client, password string, userId int64) error {
	return client.TransferChatOwnership(c.Id, password, userId)
}

// TranslateMessageText is a helper method for Client.TranslateMessageText
func (c *Chat) TranslateMessageText(client *Client, messageId int64, toLanguageCode string) (*FormattedText, error) {
	return client.TranslateMessageText(c.Id, messageId, toLanguageCode)
}

// UnpinAllMessages is a helper method for Client.UnpinAllChatMessages
func (c *Chat) UnpinAllMessages(client *Client) error {
	return client.UnpinAllChatMessages(c.Id)
}

// UnpinAllDirectMessagesTopicMessages is a helper method for Client.UnpinAllDirectMessagesChatTopicMessages
func (c *Chat) UnpinAllDirectMessagesTopicMessages(client *Client, topicId int64) error {
	return client.UnpinAllDirectMessagesChatTopicMessages(c.Id, topicId)
}

// UnpinAllForumTopicMessages is a helper method for Client.UnpinAllForumTopicMessages
func (c *Chat) UnpinAllForumTopicMessages(client *Client, forumTopicId int32) error {
	return client.UnpinAllForumTopicMessages(c.Id, forumTopicId)
}

// UnpinMessage is a helper method for Client.UnpinChatMessage
func (c *Chat) UnpinMessage(client *Client, messageId int64) error {
	return client.UnpinChatMessage(c.Id, messageId)
}

// UpgradeBasicGroupToSupergroupChat is a helper method for Client.UpgradeBasicGroupChatToSupergroupChat
func (c *Chat) UpgradeBasicGroupToSupergroupChat(client *Client) (*Chat, error) {
	return client.UpgradeBasicGroupChatToSupergroupChat(c.Id)
}

// ViewMessages is a helper method for Client.ViewMessages
func (c *Chat) ViewMessages(client *Client, forceRead bool, messageIds []int64, opts *ViewMessagesOpts) error {
	return client.ViewMessages(c.Id, forceRead, messageIds, opts)
}

// AddToDownloads is a helper method for Client.AddFileToDownloads
func (f *File) AddToDownloads(client *Client, chatId int64, messageId int64, priority int32) (*File, error) {
	return client.AddFileToDownloads(chatId, f.Id, messageId, priority)
}

// AddProfileAudio is a helper method for Client.AddProfileAudio
func (f *File) AddProfileAudio(client *Client) error {
	return client.AddProfileAudio(f.Id)
}

// CancelDownload is a helper method for Client.CancelDownloadFile
func (f *File) CancelDownload(client *Client, onlyIfPending bool) error {
	return client.CancelDownloadFile(f.Id, onlyIfPending)
}

// CancelPreliminaryUpload is a helper method for Client.CancelPreliminaryUploadFile
func (f *File) CancelPreliminaryUpload(client *Client) error {
	return client.CancelPreliminaryUploadFile(f.Id)
}

// Delete is a helper method for Client.DeleteFile
func (f *File) Delete(client *Client) error {
	return client.DeleteFile(f.Id)
}

// Download is a helper method for Client.DownloadFile
func (f *File) Download(client *Client, limit int64, offset int64, priority int32, synchronous bool) (*File, error) {
	return client.DownloadFile(f.Id, limit, offset, priority, synchronous)
}

// EditBotMediaPreview is a helper method for Client.EditBotMediaPreview
func (f *File) EditBotMediaPreview(client *Client, botUserId int64, content InputStoryContent, languageCode string) (*BotMediaPreview, error) {
	return client.EditBotMediaPreview(botUserId, content, f.Id, languageCode)
}

// GetAttachedStickerSets is a helper method for Client.GetAttachedStickerSets
func (f *File) GetAttachedStickerSets(client *Client) (*StickerSets, error) {
	return client.GetAttachedStickerSets(f.Id)
}

// Get is a helper method for Client.GetFile
func (f *File) Get(client *Client) (*File, error) {
	return client.GetFile(f.Id)
}

// GetDownloadedPrefixSize is a helper method for Client.GetFileDownloadedPrefixSize
func (f *File) GetDownloadedPrefixSize(client *Client, offset int64) (*FileDownloadedPrefixSize, error) {
	return client.GetFileDownloadedPrefixSize(f.Id, offset)
}

// GetSuggestedName is a helper method for Client.GetSuggestedFileName
func (f *File) GetSuggestedName(client *Client, directory string) (*Text, error) {
	return client.GetSuggestedFileName(directory, f.Id)
}

// IsProfileAudio is a helper method for Client.IsProfileAudio
func (f *File) IsProfileAudio(client *Client) error {
	return client.IsProfileAudio(f.Id)
}

// ReadPart is a helper method for Client.ReadFilePart
func (f *File) ReadPart(client *Client, count int64, offset int64) (*Data, error) {
	return client.ReadFilePart(count, f.Id, offset)
}

// RemoveFromDownloads is a helper method for Client.RemoveFileFromDownloads
func (f *File) RemoveFromDownloads(client *Client, deleteFromCache bool) error {
	return client.RemoveFileFromDownloads(deleteFromCache, f.Id)
}

// RemoveProfileAudio is a helper method for Client.RemoveProfileAudio
func (f *File) RemoveProfileAudio(client *Client) error {
	return client.RemoveProfileAudio(f.Id)
}

// ReportChatPhoto is a helper method for Client.ReportChatPhoto
func (f *File) ReportChatPhoto(client *Client, chatId int64, reason ReportReason, text string) error {
	return client.ReportChatPhoto(chatId, f.Id, reason, text)
}

// SetProfileAudioPosition is a helper method for Client.SetProfileAudioPosition
func (f *File) SetProfileAudioPosition(client *Client, afterFileId int32) error {
	return client.SetProfileAudioPosition(afterFileId, f.Id)
}

// ToggleDownloadIsPaused is a helper method for Client.ToggleDownloadIsPaused
func (f *File) ToggleDownloadIsPaused(client *Client, isPaused bool) error {
	return client.ToggleDownloadIsPaused(f.Id, isPaused)
}

// AddChecklistTasks is a helper method for Client.AddChecklistTasks
func (m *Message) AddChecklistTasks(client *Client, tasks []InputChecklistTask) error {
	return client.AddChecklistTasks(m.ChatId, m.Id, tasks)
}

// AddFileToDownloads is a helper method for Client.AddFileToDownloads
func (m *Message) AddFileToDownloads(client *Client, fileId int32, priority int32) (*File, error) {
	return client.AddFileToDownloads(m.ChatId, fileId, m.Id, priority)
}

// AddReaction is a helper method for Client.AddMessageReaction
func (m *Message) AddReaction(client *Client, isBig bool, reactionType ReactionType, updateRecentReactions bool) error {
	return client.AddMessageReaction(m.ChatId, isBig, m.Id, reactionType, updateRecentReactions)
}

// AddOffer is a helper method for Client.AddOffer
func (m *Message) AddOffer(client *Client, options *MessageSendOptions) (*Message, error) {
	return client.AddOffer(m.ChatId, m.Id, options)
}

// AddPendingPaidReaction is a helper method for Client.AddPendingPaidMessageReaction
func (m *Message) AddPendingPaidReaction(client *Client, starCount int64, opts *AddPendingPaidMessageReactionOpts) error {
	return client.AddPendingPaidMessageReaction(m.ChatId, m.Id, starCount, opts)
}

// ApproveSuggestedPost is a helper method for Client.ApproveSuggestedPost
func (m *Message) ApproveSuggestedPost(client *Client, sendDate int32) error {
	return client.ApproveSuggestedPost(m.ChatId, m.Id, sendDate)
}

// BlockSenderFromReplies is a helper method for Client.BlockMessageSenderFromReplies
func (m *Message) BlockSenderFromReplies(client *Client, deleteAllMessages bool, deleteMessage bool, reportSpam bool) error {
	return client.BlockMessageSenderFromReplies(deleteAllMessages, deleteMessage, m.Id, reportSpam)
}

// ClickAnimatedEmoji is a helper method for Client.ClickAnimatedEmojiMessage
func (m *Message) ClickAnimatedEmoji(client *Client) (*Sticker, error) {
	return client.ClickAnimatedEmojiMessage(m.ChatId, m.Id)
}

// ClickChatSponsored is a helper method for Client.ClickChatSponsoredMessage
func (m *Message) ClickChatSponsored(client *Client, fromFullscreen bool, isMediaClick bool) error {
	return client.ClickChatSponsoredMessage(m.ChatId, fromFullscreen, isMediaClick, m.Id)
}

// CommitPendingPaidReactions is a helper method for Client.CommitPendingPaidMessageReactions
func (m *Message) CommitPendingPaidReactions(client *Client) error {
	return client.CommitPendingPaidMessageReactions(m.ChatId, m.Id)
}

// DeclineGroupCallInvitation is a helper method for Client.DeclineGroupCallInvitation
func (m *Message) DeclineGroupCallInvitation(client *Client) error {
	return client.DeclineGroupCallInvitation(m.ChatId, m.Id)
}

// DeclineSuggestedPost is a helper method for Client.DeclineSuggestedPost
func (m *Message) DeclineSuggestedPost(client *Client, comment string) error {
	return client.DeclineSuggestedPost(m.ChatId, comment, m.Id)
}

// DeleteChatReplyMarkup is a helper method for Client.DeleteChatReplyMarkup
func (m *Message) DeleteChatReplyMarkup(client *Client) error {
	return client.DeleteChatReplyMarkup(m.ChatId, m.Id)
}

// EditBusinessCaption is a helper method for Client.EditBusinessMessageCaption
func (m *Message) EditBusinessCaption(client *Client, businessConnectionId string, showCaptionAboveMedia bool, opts *EditBusinessMessageCaptionOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageCaption(businessConnectionId, m.ChatId, m.Id, showCaptionAboveMedia, opts)
}

// EditBusinessChecklist is a helper method for Client.EditBusinessMessageChecklist
func (m *Message) EditBusinessChecklist(client *Client, businessConnectionId string, checklist *InputChecklist, opts *EditBusinessMessageChecklistOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageChecklist(businessConnectionId, m.ChatId, checklist, m.Id, opts)
}

// EditBusinessLiveLocation is a helper method for Client.EditBusinessMessageLiveLocation
func (m *Message) EditBusinessLiveLocation(client *Client, businessConnectionId string, heading int32, livePeriod int32, proximityAlertRadius int32, opts *EditBusinessMessageLiveLocationOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageLiveLocation(businessConnectionId, m.ChatId, heading, livePeriod, m.Id, proximityAlertRadius, opts)
}

// EditBusinessMedia is a helper method for Client.EditBusinessMessageMedia
func (m *Message) EditBusinessMedia(client *Client, businessConnectionId string, inputMessageContent InputMessageContent, opts *EditBusinessMessageMediaOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageMedia(businessConnectionId, m.ChatId, inputMessageContent, m.Id, opts)
}

// EditBusinessReplyMarkup is a helper method for Client.EditBusinessMessageReplyMarkup
func (m *Message) EditBusinessReplyMarkup(client *Client, businessConnectionId string, opts *EditBusinessMessageReplyMarkupOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageReplyMarkup(businessConnectionId, m.ChatId, m.Id, opts)
}

// EditBusinessText is a helper method for Client.EditBusinessMessageText
func (m *Message) EditBusinessText(client *Client, businessConnectionId string, inputMessageContent InputMessageContent, opts *EditBusinessMessageTextOpts) (*BusinessMessage, error) {
	return client.EditBusinessMessageText(businessConnectionId, m.ChatId, inputMessageContent, m.Id, opts)
}

// EditCaption is a helper method for Client.EditMessageCaption
func (m *Message) EditCaption(client *Client, showCaptionAboveMedia bool, opts *EditMessageCaptionOpts) (*Message, error) {
	return client.EditMessageCaption(m.ChatId, m.Id, showCaptionAboveMedia, opts)
}

// EditChecklist is a helper method for Client.EditMessageChecklist
func (m *Message) EditChecklist(client *Client, checklist *InputChecklist, opts *EditMessageChecklistOpts) (*Message, error) {
	return client.EditMessageChecklist(m.ChatId, checklist, m.Id, opts)
}

// EditLiveLocation is a helper method for Client.EditMessageLiveLocation
func (m *Message) EditLiveLocation(client *Client, heading int32, livePeriod int32, proximityAlertRadius int32, opts *EditMessageLiveLocationOpts) (*Message, error) {
	return client.EditMessageLiveLocation(m.ChatId, heading, livePeriod, m.Id, proximityAlertRadius, opts)
}

// EditMedia is a helper method for Client.EditMessageMedia
func (m *Message) EditMedia(client *Client, inputMessageContent InputMessageContent, opts *EditMessageMediaOpts) (*Message, error) {
	return client.EditMessageMedia(m.ChatId, inputMessageContent, m.Id, opts)
}

// EditReplyMarkup is a helper method for Client.EditMessageReplyMarkup
func (m *Message) EditReplyMarkup(client *Client, opts *EditMessageReplyMarkupOpts) (*Message, error) {
	return client.EditMessageReplyMarkup(m.ChatId, m.Id, opts)
}

// EditSchedulingState is a helper method for Client.EditMessageSchedulingState
func (m *Message) EditSchedulingState(client *Client, opts *EditMessageSchedulingStateOpts) error {
	return client.EditMessageSchedulingState(m.ChatId, m.Id, opts)
}

// EditQuickReply is a helper method for Client.EditQuickReplyMessage
func (m *Message) EditQuickReply(client *Client, inputMessageContent InputMessageContent, shortcutId int32) error {
	return client.EditQuickReplyMessage(inputMessageContent, m.Id, shortcutId)
}

// GetCallbackQueryAnswer is a helper method for Client.GetCallbackQueryAnswer
func (m *Message) GetCallbackQueryAnswer(client *Client, payload CallbackQueryPayload) (*CallbackQueryAnswer, error) {
	return client.GetCallbackQueryAnswer(m.ChatId, m.Id, payload)
}

// GetCallbackQuery is a helper method for Client.GetCallbackQueryMessage
func (m *Message) GetCallbackQuery(client *Client, callbackQueryId int64) (*Message, error) {
	return client.GetCallbackQueryMessage(callbackQueryId, m.ChatId, m.Id)
}

// GetChatPosition is a helper method for Client.GetChatMessagePosition
func (m *Message) GetChatPosition(client *Client, filter SearchMessagesFilter, opts *GetChatMessagePositionOpts) (*Count, error) {
	return client.GetChatMessagePosition(m.ChatId, filter, m.Id, opts)
}

// GetGameHighScores is a helper method for Client.GetGameHighScores
func (m *Message) GetGameHighScores(client *Client, userId int64) (*GameHighScores, error) {
	return client.GetGameHighScores(m.ChatId, m.Id, userId)
}

// GetGiveawayInfo is a helper method for Client.GetGiveawayInfo
func (m *Message) GetGiveawayInfo(client *Client) (GiveawayInfo, error) {
	return client.GetGiveawayInfo(m.ChatId, m.Id)
}

// GetLoginUrl is a helper method for Client.GetLoginUrl
func (m *Message) GetLoginUrl(client *Client, allowWriteAccess bool, buttonId int64) (*HttpUrl, error) {
	return client.GetLoginUrl(allowWriteAccess, buttonId, m.ChatId, m.Id)
}

// GetLoginUrlInfo is a helper method for Client.GetLoginUrlInfo
func (m *Message) GetLoginUrlInfo(client *Client, buttonId int64) (LoginUrlInfo, error) {
	return client.GetLoginUrlInfo(buttonId, m.ChatId, m.Id)
}

// Get is a helper method for Client.GetMessage
func (m *Message) Get(client *Client) (*Message, error) {
	return client.GetMessage(m.ChatId, m.Id)
}

// GetAddedReactions is a helper method for Client.GetMessageAddedReactions
func (m *Message) GetAddedReactions(client *Client, limit int32, offset string, opts *GetMessageAddedReactionsOpts) (*AddedReactions, error) {
	return client.GetMessageAddedReactions(m.ChatId, limit, m.Id, offset, opts)
}

// GetAuthor is a helper method for Client.GetMessageAuthor
func (m *Message) GetAuthor(client *Client) (*User, error) {
	return client.GetMessageAuthor(m.ChatId, m.Id)
}

// GetAvailableReactions is a helper method for Client.GetMessageAvailableReactions
func (m *Message) GetAvailableReactions(client *Client, rowSize int32) (*AvailableReactions, error) {
	return client.GetMessageAvailableReactions(m.ChatId, m.Id, rowSize)
}

// GetEmbeddingCode is a helper method for Client.GetMessageEmbeddingCode
func (m *Message) GetEmbeddingCode(client *Client, forAlbum bool) (*Text, error) {
	return client.GetMessageEmbeddingCode(m.ChatId, forAlbum, m.Id)
}

// GetLocally is a helper method for Client.GetMessageLocally
func (m *Message) GetLocally(client *Client) (*Message, error) {
	return client.GetMessageLocally(m.ChatId, m.Id)
}

// GetProperties is a helper method for Client.GetMessageProperties
func (m *Message) GetProperties(client *Client) (*MessageProperties, error) {
	return client.GetMessageProperties(m.ChatId, m.Id)
}

// GetPublicForwards is a helper method for Client.GetMessagePublicForwards
func (m *Message) GetPublicForwards(client *Client, limit int32, offset string) (*PublicForwards, error) {
	return client.GetMessagePublicForwards(m.ChatId, limit, m.Id, offset)
}

// GetReadDate is a helper method for Client.GetMessageReadDate
func (m *Message) GetReadDate(client *Client) (MessageReadDate, error) {
	return client.GetMessageReadDate(m.ChatId, m.Id)
}

// GetStatistics is a helper method for Client.GetMessageStatistics
func (m *Message) GetStatistics(client *Client, isDark bool) (*MessageStatistics, error) {
	return client.GetMessageStatistics(m.ChatId, isDark, m.Id)
}

// GetThread is a helper method for Client.GetMessageThread
func (m *Message) GetThread(client *Client) (*MessageThreadInfo, error) {
	return client.GetMessageThread(m.ChatId, m.Id)
}

// GetThreadHistory is a helper method for Client.GetMessageThreadHistory
func (m *Message) GetThreadHistory(client *Client, fromMessageId int64, limit int32, offset int32) (*Messages, error) {
	return client.GetMessageThreadHistory(m.ChatId, fromMessageId, limit, m.Id, offset)
}

// GetViewers is a helper method for Client.GetMessageViewers
func (m *Message) GetViewers(client *Client) (*MessageViewers, error) {
	return client.GetMessageViewers(m.ChatId, m.Id)
}

// GetPaymentReceipt is a helper method for Client.GetPaymentReceipt
func (m *Message) GetPaymentReceipt(client *Client) (*PaymentReceipt, error) {
	return client.GetPaymentReceipt(m.ChatId, m.Id)
}

// GetPollVoters is a helper method for Client.GetPollVoters
func (m *Message) GetPollVoters(client *Client, limit int32, offset int32, optionId int32) (*MessageSenders, error) {
	return client.GetPollVoters(m.ChatId, limit, m.Id, offset, optionId)
}

// GetReplied is a helper method for Client.GetRepliedMessage
func (m *Message) GetReplied(client *Client) (*Message, error) {
	return client.GetRepliedMessage(m.ChatId, m.Id)
}

// GetVideoAdvertisements is a helper method for Client.GetVideoMessageAdvertisements
func (m *Message) GetVideoAdvertisements(client *Client) (*VideoMessageAdvertisements, error) {
	return client.GetVideoMessageAdvertisements(m.ChatId, m.Id)
}

// MarkChecklistTasksAsDone is a helper method for Client.MarkChecklistTasksAsDone
func (m *Message) MarkChecklistTasksAsDone(client *Client, markedAsDoneTaskIds []int32, markedAsNotDoneTaskIds []int32) error {
	return client.MarkChecklistTasksAsDone(m.ChatId, markedAsDoneTaskIds, markedAsNotDoneTaskIds, m.Id)
}

// OpenContent is a helper method for Client.OpenMessageContent
func (m *Message) OpenContent(client *Client) error {
	return client.OpenMessageContent(m.ChatId, m.Id)
}

// PinChat is a helper method for Client.PinChatMessage
func (m *Message) PinChat(client *Client, disableNotification bool, onlyForSelf bool) error {
	return client.PinChatMessage(m.ChatId, disableNotification, m.Id, onlyForSelf)
}

// ProcessGiftPurchaseOffer is a helper method for Client.ProcessGiftPurchaseOffer
func (m *Message) ProcessGiftPurchaseOffer(client *Client, accept bool) error {
	return client.ProcessGiftPurchaseOffer(accept, m.Id)
}

// RateSpeechRecognition is a helper method for Client.RateSpeechRecognition
func (m *Message) RateSpeechRecognition(client *Client, isGood bool) error {
	return client.RateSpeechRecognition(m.ChatId, isGood, m.Id)
}

// ReadBusiness is a helper method for Client.ReadBusinessMessage
func (m *Message) ReadBusiness(client *Client, businessConnectionId string) error {
	return client.ReadBusinessMessage(businessConnectionId, m.ChatId, m.Id)
}

// RecognizeSpeech is a helper method for Client.RecognizeSpeech
func (m *Message) RecognizeSpeech(client *Client) error {
	return client.RecognizeSpeech(m.ChatId, m.Id)
}

// RemoveReaction is a helper method for Client.RemoveMessageReaction
func (m *Message) RemoveReaction(client *Client, reactionType ReactionType) error {
	return client.RemoveMessageReaction(m.ChatId, m.Id, reactionType)
}

// RemovePendingPaidReactions is a helper method for Client.RemovePendingPaidMessageReactions
func (m *Message) RemovePendingPaidReactions(client *Client) error {
	return client.RemovePendingPaidMessageReactions(m.ChatId, m.Id)
}

// ReportChatSponsored is a helper method for Client.ReportChatSponsoredMessage
func (m *Message) ReportChatSponsored(client *Client, optionId []byte) (ReportSponsoredResult, error) {
	return client.ReportChatSponsoredMessage(m.ChatId, m.Id, optionId)
}

// ReportReactions is a helper method for Client.ReportMessageReactions
func (m *Message) ReportReactions(client *Client) error {
	return client.ReportMessageReactions(m.ChatId, m.Id, m.SenderId)
}

// ReportSupergroupAntiSpamFalsePositive is a helper method for Client.ReportSupergroupAntiSpamFalsePositive
func (m *Message) ReportSupergroupAntiSpamFalsePositive(client *Client, supergroupId int64) error {
	return client.ReportSupergroupAntiSpamFalsePositive(m.Id, supergroupId)
}

// SetBusinessIsPinned is a helper method for Client.SetBusinessMessageIsPinned
func (m *Message) SetBusinessIsPinned(client *Client, businessConnectionId string) error {
	return client.SetBusinessMessageIsPinned(businessConnectionId, m.ChatId, m.IsPinned, m.Id)
}

// SetGameScore is a helper method for Client.SetGameScore
func (m *Message) SetGameScore(client *Client, editMessage bool, force bool, score int32, userId int64) (*Message, error) {
	return client.SetGameScore(m.ChatId, editMessage, force, m.Id, score, userId)
}

// SetFactCheck is a helper method for Client.SetMessageFactCheck
func (m *Message) SetFactCheck(client *Client, opts *SetMessageFactCheckOpts) error {
	return client.SetMessageFactCheck(m.ChatId, m.Id, opts)
}

// SetReactions is a helper method for Client.SetMessageReactions
func (m *Message) SetReactions(client *Client, isBig bool, reactionTypes []ReactionType) error {
	return client.SetMessageReactions(m.ChatId, isBig, m.Id, reactionTypes)
}

// SetPaidReactionType is a helper method for Client.SetPaidMessageReactionType
func (m *Message) SetPaidReactionType(client *Client, typeField PaidReactionType) error {
	return client.SetPaidMessageReactionType(m.ChatId, m.Id, typeField)
}

// SetPollAnswer is a helper method for Client.SetPollAnswer
func (m *Message) SetPollAnswer(client *Client, optionIds []int32) error {
	return client.SetPollAnswer(m.ChatId, m.Id, optionIds)
}

// ShareChatWithBot is a helper method for Client.ShareChatWithBot
func (m *Message) ShareChatWithBot(client *Client, buttonId int32, onlyCheck bool, sharedChatId int64) error {
	return client.ShareChatWithBot(buttonId, m.ChatId, m.Id, onlyCheck, sharedChatId)
}

// ShareUsersWithBot is a helper method for Client.ShareUsersWithBot
func (m *Message) ShareUsersWithBot(client *Client, buttonId int32, onlyCheck bool, sharedUserIds []int64) error {
	return client.ShareUsersWithBot(buttonId, m.ChatId, m.Id, onlyCheck, sharedUserIds)
}

// StopBusinessPoll is a helper method for Client.StopBusinessPoll
func (m *Message) StopBusinessPoll(client *Client, businessConnectionId string, opts *StopBusinessPollOpts) (*BusinessMessage, error) {
	return client.StopBusinessPoll(businessConnectionId, m.ChatId, m.Id, opts)
}

// StopPoll is a helper method for Client.StopPoll
func (m *Message) StopPoll(client *Client, opts *StopPollOpts) error {
	return client.StopPoll(m.ChatId, m.Id, opts)
}

// Summarize is a helper method for Client.SummarizeMessage
func (m *Message) Summarize(client *Client, opts *SummarizeMessageOpts) (*FormattedText, error) {
	return client.SummarizeMessage(m.ChatId, m.Id, opts)
}

// TranslateText is a helper method for Client.TranslateMessageText
func (m *Message) TranslateText(client *Client, toLanguageCode string) (*FormattedText, error) {
	return client.TranslateMessageText(m.ChatId, m.Id, toLanguageCode)
}

// UnpinChat is a helper method for Client.UnpinChatMessage
func (m *Message) UnpinChat(client *Client) error {
	return client.UnpinChatMessage(m.ChatId, m.Id)
}

// Get is a helper method for Client.GetRemoteFile
func (r *RemoteFile) Get(client *Client, opts *GetRemoteFileOpts) (*File, error) {
	return client.GetRemoteFile(r.Id, opts)
}

// AddChatMember is a helper method for Client.AddChatMember
func (u *User) AddChatMember(client *Client, chatId int64, forwardLimit int32) (*FailedToAddMembers, error) {
	return client.AddChatMember(chatId, forwardLimit, u.Id)
}

// AddContact is a helper method for Client.AddContact
func (u *User) AddContact(client *Client, sharePhoneNumber bool, opts *AddContactOpts) error {
	return client.AddContact(sharePhoneNumber, u.Id, opts)
}

// AddStickerToSet is a helper method for Client.AddStickerToSet
func (u *User) AddStickerToSet(client *Client, name string, sticker *InputSticker) error {
	return client.AddStickerToSet(name, sticker, u.Id)
}

// AllowUnpaidMessagesFrom is a helper method for Client.AllowUnpaidMessagesFromUser
func (u *User) AllowUnpaidMessagesFrom(client *Client, refundPayments bool) error {
	return client.AllowUnpaidMessagesFromUser(refundPayments, u.Id)
}

// CanSendMessageTo is a helper method for Client.CanSendMessageToUser
func (u *User) CanSendMessageTo(client *Client, onlyLocal bool) (CanSendMessageToUserResult, error) {
	return client.CanSendMessageToUser(onlyLocal, u.Id)
}

// CreateCall is a helper method for Client.CreateCall
func (u *User) CreateCall(client *Client, isVideo bool, protocol *CallProtocol) (*CallId, error) {
	return client.CreateCall(isVideo, protocol, u.Id)
}

// CreateNewSecretChat is a helper method for Client.CreateNewSecretChat
func (u *User) CreateNewSecretChat(client *Client) (*Chat, error) {
	return client.CreateNewSecretChat(u.Id)
}

// CreateNewStickerSet is a helper method for Client.CreateNewStickerSet
func (u *User) CreateNewStickerSet(client *Client, name string, needsRepainting bool, stickerType StickerType, stickers []InputSticker, title string, opts *CreateNewStickerSetOpts) (*StickerSet, error) {
	return client.CreateNewStickerSet(name, needsRepainting, stickerType, stickers, title, u.Id, opts)
}

// CreatePrivateChat is a helper method for Client.CreatePrivateChat
func (u *User) CreatePrivateChat(client *Client, force bool) (*Chat, error) {
	return client.CreatePrivateChat(force, u.Id)
}

// EditStarSubscription is a helper method for Client.EditUserStarSubscription
func (u *User) EditStarSubscription(client *Client, isCanceled bool, telegramPaymentChargeId string) error {
	return client.EditUserStarSubscription(isCanceled, telegramPaymentChargeId, u.Id)
}

// GetGameHighScores is a helper method for Client.GetGameHighScores
func (u *User) GetGameHighScores(client *Client, chatId int64, messageId int64) (*GameHighScores, error) {
	return client.GetGameHighScores(chatId, messageId, u.Id)
}

// GetGroupsInCommon is a helper method for Client.GetGroupsInCommon
func (u *User) GetGroupsInCommon(client *Client, limit int32, offsetChatId int64) (*Chats, error) {
	return client.GetGroupsInCommon(limit, offsetChatId, u.Id)
}

// GetInlineGameHighScores is a helper method for Client.GetInlineGameHighScores
func (u *User) GetInlineGameHighScores(client *Client, inlineMessageId string) (*GameHighScores, error) {
	return client.GetInlineGameHighScores(inlineMessageId, u.Id)
}

// GetMenuButton is a helper method for Client.GetMenuButton
func (u *User) GetMenuButton(client *Client) (*BotMenuButton, error) {
	return client.GetMenuButton(u.Id)
}

// GetPaidMessageRevenue is a helper method for Client.GetPaidMessageRevenue
func (u *User) GetPaidMessageRevenue(client *Client) (*StarCount, error) {
	return client.GetPaidMessageRevenue(u.Id)
}

// GetStarGiftPaymentOptions is a helper method for Client.GetStarGiftPaymentOptions
func (u *User) GetStarGiftPaymentOptions(client *Client) (*StarPaymentOptions, error) {
	return client.GetStarGiftPaymentOptions(u.Id)
}

// Get is a helper method for Client.GetUser
func (u *User) Get(client *Client) (*User, error) {
	return client.GetUser(u.Id)
}

// GetChatBoosts is a helper method for Client.GetUserChatBoosts
func (u *User) GetChatBoosts(client *Client, chatId int64) (*FoundChatBoosts, error) {
	return client.GetUserChatBoosts(chatId, u.Id)
}

// GetFullInfo is a helper method for Client.GetUserFullInfo
func (u *User) GetFullInfo(client *Client) (*UserFullInfo, error) {
	return client.GetUserFullInfo(u.Id)
}

// GetProfileAudios is a helper method for Client.GetUserProfileAudios
func (u *User) GetProfileAudios(client *Client, limit int32, offset int32) (*Audios, error) {
	return client.GetUserProfileAudios(limit, offset, u.Id)
}

// GetProfilePhotos is a helper method for Client.GetUserProfilePhotos
func (u *User) GetProfilePhotos(client *Client, limit int32, offset int32) (*ChatPhotos, error) {
	return client.GetUserProfilePhotos(limit, offset, u.Id)
}

// GetSupportInfo is a helper method for Client.GetUserSupportInfo
func (u *User) GetSupportInfo(client *Client) (*UserSupportInfo, error) {
	return client.GetUserSupportInfo(u.Id)
}

// GiftPremiumWithStars is a helper method for Client.GiftPremiumWithStars
func (u *User) GiftPremiumWithStars(client *Client, monthCount int32, starCount int64, text *FormattedText) error {
	return client.GiftPremiumWithStars(monthCount, starCount, text, u.Id)
}

// InviteGroupCallParticipant is a helper method for Client.InviteGroupCallParticipant
func (u *User) InviteGroupCallParticipant(client *Client, groupCallId int32, isVideo bool) (InviteGroupCallParticipantResult, error) {
	return client.InviteGroupCallParticipant(groupCallId, isVideo, u.Id)
}

// PlaceGiftAuctionBid is a helper method for Client.PlaceGiftAuctionBid
func (u *User) PlaceGiftAuctionBid(client *Client, giftId int64, isPrivate bool, starCount int64, text *FormattedText) error {
	return client.PlaceGiftAuctionBid(giftId, isPrivate, starCount, text, u.Id)
}

// ProcessChatJoinRequest is a helper method for Client.ProcessChatJoinRequest
func (u *User) ProcessChatJoinRequest(client *Client, approve bool, chatId int64) error {
	return client.ProcessChatJoinRequest(approve, chatId, u.Id)
}

// RefundStarPayment is a helper method for Client.RefundStarPayment
func (u *User) RefundStarPayment(client *Client, telegramPaymentChargeId string) error {
	return client.RefundStarPayment(telegramPaymentChargeId, u.Id)
}

// ReplaceStickerInSet is a helper method for Client.ReplaceStickerInSet
func (u *User) ReplaceStickerInSet(client *Client, name string, newSticker *InputSticker, oldSticker InputFile) error {
	return client.ReplaceStickerInSet(name, newSticker, oldSticker, u.Id)
}

// SavePreparedInlineMessage is a helper method for Client.SavePreparedInlineMessage
func (u *User) SavePreparedInlineMessage(client *Client, chatTypes *TargetChatTypes, result InputInlineQueryResult) (*PreparedInlineMessageId, error) {
	return client.SavePreparedInlineMessage(chatTypes, result, u.Id)
}

// SetGameScore is a helper method for Client.SetGameScore
func (u *User) SetGameScore(client *Client, chatId int64, editMessage bool, force bool, messageId int64, score int32) (*Message, error) {
	return client.SetGameScore(chatId, editMessage, force, messageId, score, u.Id)
}

// SetInlineGameScore is a helper method for Client.SetInlineGameScore
func (u *User) SetInlineGameScore(client *Client, editMessage bool, force bool, inlineMessageId string, score int32) error {
	return client.SetInlineGameScore(editMessage, force, inlineMessageId, score, u.Id)
}

// SetMenuButton is a helper method for Client.SetMenuButton
func (u *User) SetMenuButton(client *Client, menuButton *BotMenuButton) error {
	return client.SetMenuButton(menuButton, u.Id)
}

// SetPassportElementErrors is a helper method for Client.SetPassportElementErrors
func (u *User) SetPassportElementErrors(client *Client, errors []InputPassportElementError) error {
	return client.SetPassportElementErrors(errors, u.Id)
}

// SetStickerSetThumbnail is a helper method for Client.SetStickerSetThumbnail
func (u *User) SetStickerSetThumbnail(client *Client, name string, opts *SetStickerSetThumbnailOpts) error {
	return client.SetStickerSetThumbnail(name, u.Id, opts)
}

// SetEmojiStatus is a helper method for Client.SetUserEmojiStatus
func (u *User) SetEmojiStatus(client *Client) error {
	return client.SetUserEmojiStatus(u.EmojiStatus, u.Id)
}

// SetNote is a helper method for Client.SetUserNote
func (u *User) SetNote(client *Client, note *FormattedText) error {
	return client.SetUserNote(note, u.Id)
}

// SetPersonalProfilePhoto is a helper method for Client.SetUserPersonalProfilePhoto
func (u *User) SetPersonalProfilePhoto(client *Client, photo InputChatPhoto) error {
	return client.SetUserPersonalProfilePhoto(photo, u.Id)
}

// SetSupportInfo is a helper method for Client.SetUserSupportInfo
func (u *User) SetSupportInfo(client *Client, message *FormattedText) (*UserSupportInfo, error) {
	return client.SetUserSupportInfo(message, u.Id)
}

// SharePhoneNumber is a helper method for Client.SharePhoneNumber
func (u *User) SharePhoneNumber(client *Client) error {
	return client.SharePhoneNumber(u.Id)
}

// SuggestBirthdate is a helper method for Client.SuggestUserBirthdate
func (u *User) SuggestBirthdate(client *Client, birthdate *Birthdate) error {
	return client.SuggestUserBirthdate(birthdate, u.Id)
}

// SuggestProfilePhoto is a helper method for Client.SuggestUserProfilePhoto
func (u *User) SuggestProfilePhoto(client *Client, photo InputChatPhoto) error {
	return client.SuggestUserProfilePhoto(photo, u.Id)
}

// TransferChatOwnership is a helper method for Client.TransferChatOwnership
func (u *User) TransferChatOwnership(client *Client, chatId int64, password string) error {
	return client.TransferChatOwnership(chatId, password, u.Id)
}

// UploadStickerFile is a helper method for Client.UploadStickerFile
func (u *User) UploadStickerFile(client *Client, sticker InputFile, stickerFormat StickerFormat) (*File, error) {
	return client.UploadStickerFile(sticker, stickerFormat, u.Id)
}
