// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package gotdbot

// AddContactOpts contains optional parameters for AddContact
type AddContactOpts struct {
	Contact *ImportedContact
}

// AddLocalMessageOpts contains optional parameters for AddLocalMessage
type AddLocalMessageOpts struct {
	ReplyTo InputMessageReplyTo
}

// AddPendingPaidMessageReactionOpts contains optional parameters for AddPendingPaidMessageReaction
type AddPendingPaidMessageReactionOpts struct {
	TypeField PaidReactionType
}

// AnswerInlineQueryOpts contains optional parameters for AnswerInlineQuery
type AnswerInlineQueryOpts struct {
	Button *InlineQueryResultsButton
}

// CreateNewBasicGroupChatOpts contains optional parameters for CreateNewBasicGroupChat
type CreateNewBasicGroupChatOpts struct {
	UserIds []int64
}

// CreateNewStickerSetOpts contains optional parameters for CreateNewStickerSet
type CreateNewStickerSetOpts struct {
	Source string
}

// CreateNewSupergroupChatOpts contains optional parameters for CreateNewSupergroupChat
type CreateNewSupergroupChatOpts struct {
	Location *ChatLocation
}

// DecryptGroupCallDataOpts contains optional parameters for DecryptGroupCallData
type DecryptGroupCallDataOpts struct {
	DataChannel GroupCallDataChannel
}

// DeleteCommandsOpts contains optional parameters for DeleteCommands
type DeleteCommandsOpts struct {
	Scope BotCommandScope
}

// EditBusinessMessageCaptionOpts contains optional parameters for EditBusinessMessageCaption
type EditBusinessMessageCaptionOpts struct {
	Caption     *FormattedText
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageChecklistOpts contains optional parameters for EditBusinessMessageChecklist
type EditBusinessMessageChecklistOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageLiveLocationOpts contains optional parameters for EditBusinessMessageLiveLocation
type EditBusinessMessageLiveLocationOpts struct {
	Location    *Location
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageMediaOpts contains optional parameters for EditBusinessMessageMedia
type EditBusinessMessageMediaOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageReplyMarkupOpts contains optional parameters for EditBusinessMessageReplyMarkup
type EditBusinessMessageReplyMarkupOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditBusinessMessageTextOpts contains optional parameters for EditBusinessMessageText
type EditBusinessMessageTextOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageCaptionOpts contains optional parameters for EditInlineMessageCaption
type EditInlineMessageCaptionOpts struct {
	Caption     *FormattedText
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageLiveLocationOpts contains optional parameters for EditInlineMessageLiveLocation
type EditInlineMessageLiveLocationOpts struct {
	Location    *Location
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageMediaOpts contains optional parameters for EditInlineMessageMedia
type EditInlineMessageMediaOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageReplyMarkupOpts contains optional parameters for EditInlineMessageReplyMarkup
type EditInlineMessageReplyMarkupOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditInlineMessageTextOpts contains optional parameters for EditInlineMessageText
type EditInlineMessageTextOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditMessageCaptionOpts contains optional parameters for EditMessageCaption
type EditMessageCaptionOpts struct {
	Caption     *FormattedText
	ReplyMarkup ReplyMarkup
}

// EditMessageChecklistOpts contains optional parameters for EditMessageChecklist
type EditMessageChecklistOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditMessageLiveLocationOpts contains optional parameters for EditMessageLiveLocation
type EditMessageLiveLocationOpts struct {
	Location    *Location
	ReplyMarkup ReplyMarkup
}

// EditMessageMediaOpts contains optional parameters for EditMessageMedia
type EditMessageMediaOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditMessageReplyMarkupOpts contains optional parameters for EditMessageReplyMarkup
type EditMessageReplyMarkupOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditMessageSchedulingStateOpts contains optional parameters for EditMessageSchedulingState
type EditMessageSchedulingStateOpts struct {
	SchedulingState MessageSchedulingState
}

// EditMessageTextOpts contains optional parameters for EditMessageText
type EditMessageTextOpts struct {
	ReplyMarkup ReplyMarkup
}

// EditStoryOpts contains optional parameters for EditStory
type EditStoryOpts struct {
	Areas   *InputStoryAreas
	Caption *FormattedText
	Content InputStoryContent
}

// FinishFileGenerationOpts contains optional parameters for FinishFileGeneration
type FinishFileGenerationOpts struct {
	Error *Error
}

// ForwardMessagesOpts contains optional parameters for ForwardMessages
type ForwardMessagesOpts struct {
	Options *MessageSendOptions
	TopicId MessageTopic
}

// GetChatEventLogOpts contains optional parameters for GetChatEventLog
type GetChatEventLogOpts struct {
	Filters *ChatEventLogFilters
}

// GetChatInviteLinkMembersOpts contains optional parameters for GetChatInviteLinkMembers
type GetChatInviteLinkMembersOpts struct {
	OffsetMember *ChatInviteLinkMember
}

// GetChatJoinRequestsOpts contains optional parameters for GetChatJoinRequests
type GetChatJoinRequestsOpts struct {
	OffsetRequest *ChatJoinRequest
}

// GetChatMessageCalendarOpts contains optional parameters for GetChatMessageCalendar
type GetChatMessageCalendarOpts struct {
	TopicId MessageTopic
}

// GetChatMessageCountOpts contains optional parameters for GetChatMessageCount
type GetChatMessageCountOpts struct {
	TopicId MessageTopic
}

// GetChatMessagePositionOpts contains optional parameters for GetChatMessagePosition
type GetChatMessagePositionOpts struct {
	TopicId MessageTopic
}

// GetChatNotificationSettingsExceptionsOpts contains optional parameters for GetChatNotificationSettingsExceptions
type GetChatNotificationSettingsExceptionsOpts struct {
	Scope NotificationSettingsScope
}

// GetChatsOpts contains optional parameters for GetChats
type GetChatsOpts struct {
	ChatList ChatList
}

// GetChatStoryInteractionsOpts contains optional parameters for GetChatStoryInteractions
type GetChatStoryInteractionsOpts struct {
	ReactionType ReactionType
}

// GetCommandsOpts contains optional parameters for GetCommands
type GetCommandsOpts struct {
	Scope BotCommandScope
}

// GetGroupCallStreamSegmentOpts contains optional parameters for GetGroupCallStreamSegment
type GetGroupCallStreamSegmentOpts struct {
	VideoQuality GroupCallVideoQuality
}

// GetInlineQueryResultsOpts contains optional parameters for GetInlineQueryResults
type GetInlineQueryResultsOpts struct {
	UserLocation *Location
}

// GetKeywordEmojisOpts contains optional parameters for GetKeywordEmojis
type GetKeywordEmojisOpts struct {
	InputLanguageCodes []string
}

// GetLinkPreviewOpts contains optional parameters for GetLinkPreview
type GetLinkPreviewOpts struct {
	LinkPreviewOptions *LinkPreviewOptions
}

// GetMessageAddedReactionsOpts contains optional parameters for GetMessageAddedReactions
type GetMessageAddedReactionsOpts struct {
	ReactionType ReactionType
}

// GetPaymentFormOpts contains optional parameters for GetPaymentForm
type GetPaymentFormOpts struct {
	Theme *ThemeParameters
}

// GetRemoteFileOpts contains optional parameters for GetRemoteFile
type GetRemoteFileOpts struct {
	FileType FileType
}

// GetStarTransactionsOpts contains optional parameters for GetStarTransactions
type GetStarTransactionsOpts struct {
	Direction      TransactionDirection
	SubscriptionId string
}

// GetStoryInteractionsOpts contains optional parameters for GetStoryInteractions
type GetStoryInteractionsOpts struct {
	Query string
}

// GetSupergroupMembersOpts contains optional parameters for GetSupergroupMembers
type GetSupergroupMembersOpts struct {
	Filter SupergroupMembersFilter
}

// GetTonTransactionsOpts contains optional parameters for GetTonTransactions
type GetTonTransactionsOpts struct {
	Direction TransactionDirection
}

// JoinVideoChatOpts contains optional parameters for JoinVideoChat
type JoinVideoChatOpts struct {
	ParticipantId MessageSender
}

// LoadChatsOpts contains optional parameters for LoadChats
type LoadChatsOpts struct {
	ChatList ChatList
}

// OpenWebAppOpts contains optional parameters for OpenWebApp
type OpenWebAppOpts struct {
	ReplyTo InputMessageReplyTo
	TopicId MessageTopic
}

// OptimizeStorageOpts contains optional parameters for OptimizeStorage
type OptimizeStorageOpts struct {
	ChatIds        []int64
	ExcludeChatIds []int64
	FileTypes      []FileType
}

// PingProxyOpts contains optional parameters for PingProxy
type PingProxyOpts struct {
	Proxy *Proxy
}

// PostStoryOpts contains optional parameters for PostStory
type PostStoryOpts struct {
	Areas           *InputStoryAreas
	Caption         *FormattedText
	FromStoryFullId *StoryFullId
}

// PreliminaryUploadFileOpts contains optional parameters for PreliminaryUploadFile
type PreliminaryUploadFileOpts struct {
	FileType FileType
}

// RecoverAuthenticationPasswordOpts contains optional parameters for RecoverAuthenticationPassword
type RecoverAuthenticationPasswordOpts struct {
	NewHint     string
	NewPassword string
}

// RecoverPasswordOpts contains optional parameters for RecoverPassword
type RecoverPasswordOpts struct {
	NewHint     string
	NewPassword string
}

// ResendAuthenticationCodeOpts contains optional parameters for ResendAuthenticationCode
type ResendAuthenticationCodeOpts struct {
	Reason ResendCodeReason
}

// ResendMessagesOpts contains optional parameters for ResendMessages
type ResendMessagesOpts struct {
	Quote *InputTextQuote
}

// ResendPhoneNumberCodeOpts contains optional parameters for ResendPhoneNumberCode
type ResendPhoneNumberCodeOpts struct {
	Reason ResendCodeReason
}

// SearchChatMembersOpts contains optional parameters for SearchChatMembers
type SearchChatMembersOpts struct {
	Filter ChatMembersFilter
}

// SearchChatMessagesOpts contains optional parameters for SearchChatMessages
type SearchChatMessagesOpts struct {
	Filter   SearchMessagesFilter
	SenderId MessageSender
	TopicId  MessageTopic
}

// SearchContactsOpts contains optional parameters for SearchContacts
type SearchContactsOpts struct {
	Query string
}

// SearchEmojisOpts contains optional parameters for SearchEmojis
type SearchEmojisOpts struct {
	InputLanguageCodes []string
}

// SearchFileDownloadsOpts contains optional parameters for SearchFileDownloads
type SearchFileDownloadsOpts struct {
	Query string
}

// SearchMessagesOpts contains optional parameters for SearchMessages
type SearchMessagesOpts struct {
	ChatList       ChatList
	ChatTypeFilter SearchMessagesChatTypeFilter
	Filter         SearchMessagesFilter
}

// SearchSavedMessagesOpts contains optional parameters for SearchSavedMessages
type SearchSavedMessagesOpts struct {
	Tag ReactionType
}

// SearchSecretMessagesOpts contains optional parameters for SearchSecretMessages
type SearchSecretMessagesOpts struct {
	Filter SearchMessagesFilter
}

// SearchStickersOpts contains optional parameters for SearchStickers
type SearchStickersOpts struct {
	InputLanguageCodes []string
	Query              string
}

// SendBusinessMessageOpts contains optional parameters for SendBusinessMessage
type SendBusinessMessageOpts struct {
	ReplyMarkup ReplyMarkup
	ReplyTo     InputMessageReplyTo
}

// SendBusinessMessageAlbumOpts contains optional parameters for SendBusinessMessageAlbum
type SendBusinessMessageAlbumOpts struct {
	ReplyTo InputMessageReplyTo
}

// SendChatActionOpts contains optional parameters for SendChatAction
type SendChatActionOpts struct {
	Action  ChatAction
	TopicId MessageTopic
}

// SendInlineQueryResultMessageOpts contains optional parameters for SendInlineQueryResultMessage
type SendInlineQueryResultMessageOpts struct {
	Options *MessageSendOptions
	ReplyTo InputMessageReplyTo
	TopicId MessageTopic
}

// SendMessageOpts contains optional parameters for SendMessage
type SendMessageOpts struct {
	Options     *MessageSendOptions
	ReplyMarkup ReplyMarkup
	ReplyTo     InputMessageReplyTo
	TopicId     MessageTopic
}

// SendMessageAlbumOpts contains optional parameters for SendMessageAlbum
type SendMessageAlbumOpts struct {
	Options *MessageSendOptions
	ReplyTo InputMessageReplyTo
	TopicId MessageTopic
}

// SendPaymentFormOpts contains optional parameters for SendPaymentForm
type SendPaymentFormOpts struct {
	Credentials InputCredentials
}

// SendPhoneNumberCodeOpts contains optional parameters for SendPhoneNumberCode
type SendPhoneNumberCodeOpts struct {
	Settings *PhoneNumberAuthenticationSettings
}

// SetAuthenticationPhoneNumberOpts contains optional parameters for SetAuthenticationPhoneNumber
type SetAuthenticationPhoneNumberOpts struct {
	Settings *PhoneNumberAuthenticationSettings
}

// SetBusinessAccountProfilePhotoOpts contains optional parameters for SetBusinessAccountProfilePhoto
type SetBusinessAccountProfilePhotoOpts struct {
	Photo InputChatPhoto
}

// SetBusinessOpeningHoursOpts contains optional parameters for SetBusinessOpeningHours
type SetBusinessOpeningHoursOpts struct {
	OpeningHours *BusinessOpeningHours
}

// SetChatAffiliateProgramOpts contains optional parameters for SetChatAffiliateProgram
type SetChatAffiliateProgramOpts struct {
	Parameters *AffiliateProgramParameters
}

// SetChatBackgroundOpts contains optional parameters for SetChatBackground
type SetChatBackgroundOpts struct {
	Background InputBackground
	TypeField  BackgroundType
}

// SetChatDraftMessageOpts contains optional parameters for SetChatDraftMessage
type SetChatDraftMessageOpts struct {
	DraftMessage *DraftMessage
	TopicId      MessageTopic
}

// SetChatEmojiStatusOpts contains optional parameters for SetChatEmojiStatus
type SetChatEmojiStatusOpts struct {
	EmojiStatus *EmojiStatus
}

// SetChatPhotoOpts contains optional parameters for SetChatPhoto
type SetChatPhotoOpts struct {
	Photo InputChatPhoto
}

// SetCommandsOpts contains optional parameters for SetCommands
type SetCommandsOpts struct {
	Scope BotCommandScope
}

// SetDefaultBackgroundOpts contains optional parameters for SetDefaultBackground
type SetDefaultBackgroundOpts struct {
	Background InputBackground
	TypeField  BackgroundType
}

// SetGiftResalePriceOpts contains optional parameters for SetGiftResalePrice
type SetGiftResalePriceOpts struct {
	Price GiftResalePrice
}

// SetMessageFactCheckOpts contains optional parameters for SetMessageFactCheck
type SetMessageFactCheckOpts struct {
	Text *FormattedText
}

// SetMessageSenderBlockListOpts contains optional parameters for SetMessageSenderBlockList
type SetMessageSenderBlockListOpts struct {
	BlockList BlockList
}

// SetNetworkTypeOpts contains optional parameters for SetNetworkType
type SetNetworkTypeOpts struct {
	TypeField NetworkType
}

// SetOptionOpts contains optional parameters for SetOption
type SetOptionOpts struct {
	Value OptionValue
}

// SetPasswordOpts contains optional parameters for SetPassword
type SetPasswordOpts struct {
	NewHint                 string
	NewPassword             string
	NewRecoveryEmailAddress string
}

// SetStickerMaskPositionOpts contains optional parameters for SetStickerMaskPosition
type SetStickerMaskPositionOpts struct {
	MaskPosition *MaskPosition
}

// SetStickerSetThumbnailOpts contains optional parameters for SetStickerSetThumbnail
type SetStickerSetThumbnailOpts struct {
	Format    StickerFormat
	Thumbnail InputFile
}

// SetStoryReactionOpts contains optional parameters for SetStoryReaction
type SetStoryReactionOpts struct {
	ReactionType ReactionType
}

// StopBusinessPollOpts contains optional parameters for StopBusinessPoll
type StopBusinessPollOpts struct {
	ReplyMarkup ReplyMarkup
}

// StopPollOpts contains optional parameters for StopPoll
type StopPollOpts struct {
	ReplyMarkup ReplyMarkup
}

// SummarizeMessageOpts contains optional parameters for SummarizeMessage
type SummarizeMessageOpts struct {
	TranslateToLanguageCode string
}

// ValidateOrderInfoOpts contains optional parameters for ValidateOrderInfo
type ValidateOrderInfoOpts struct {
	OrderInfo *OrderInfo
}

// ViewMessagesOpts contains optional parameters for ViewMessages
type ViewMessagesOpts struct {
	Source MessageSource
}
