// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateLanguagePackStrings struct {
	Filter   filters.UpdateLanguagePackStrings
	Response func(ctx *ext.Context) error
}

func NewUpdateLanguagePackStrings(filter filters.UpdateLanguagePackStrings, response func(ctx *ext.Context) error) *UpdateLanguagePackStrings {
	return &UpdateLanguagePackStrings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateLanguagePackStrings) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateLanguagePackStrings
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateLanguagePackStrings) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
