// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateChatDraftMessage struct {
	Filter   filters.UpdateChatDraftMessage
	Response func(ctx *ext.Context) error
}

func NewUpdateChatDraftMessage(filter filters.UpdateChatDraftMessage, response func(ctx *ext.Context) error) *UpdateChatDraftMessage {
	return &UpdateChatDraftMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatDraftMessage) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateChatDraftMessage
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatDraftMessage) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
