// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateSpeechRecognitionTrial struct {
	Filter   filters.UpdateSpeechRecognitionTrial
	Response func(ctx *ext.Context) error
}

func NewUpdateSpeechRecognitionTrial(filter filters.UpdateSpeechRecognitionTrial, response func(ctx *ext.Context) error) *UpdateSpeechRecognitionTrial {
	return &UpdateSpeechRecognitionTrial{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSpeechRecognitionTrial) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateSpeechRecognitionTrial
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSpeechRecognitionTrial) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
