// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateActiveNotifications struct {
	Filter   filters.UpdateActiveNotifications
	Response func(ctx *ext.Context) error
}

func NewUpdateActiveNotifications(filter filters.UpdateActiveNotifications, response func(ctx *ext.Context) error) *UpdateActiveNotifications {
	return &UpdateActiveNotifications{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateActiveNotifications) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateActiveNotifications
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateActiveNotifications) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
