// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateGroupCallMessageLevels struct {
	Filter   filters.UpdateGroupCallMessageLevels
	Response func(ctx *ext.Context) error
}

func NewUpdateGroupCallMessageLevels(filter filters.UpdateGroupCallMessageLevels, response func(ctx *ext.Context) error) *UpdateGroupCallMessageLevels {
	return &UpdateGroupCallMessageLevels{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallMessageLevels) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateGroupCallMessageLevels
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallMessageLevels) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
