// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateAuthorizationState struct {
	Filter   filters.UpdateAuthorizationState
	Response func(ctx *ext.Context) error
}

func NewUpdateAuthorizationState(filter filters.UpdateAuthorizationState, response func(ctx *ext.Context) error) *UpdateAuthorizationState {
	return &UpdateAuthorizationState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAuthorizationState) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateAuthorizationState
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAuthorizationState) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
