// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateChatReadOutbox struct {
	Filter   filters.UpdateChatReadOutbox
	Response func(ctx *ext.Context) error
}

func NewUpdateChatReadOutbox(filter filters.UpdateChatReadOutbox, response func(ctx *ext.Context) error) *UpdateChatReadOutbox {
	return &UpdateChatReadOutbox{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatReadOutbox) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateChatReadOutbox
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatReadOutbox) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
