// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateDefaultBackground struct {
	Filter   filters.UpdateDefaultBackground
	Response func(ctx *ext.Context) error
}

func NewUpdateDefaultBackground(filter filters.UpdateDefaultBackground, response func(ctx *ext.Context) error) *UpdateDefaultBackground {
	return &UpdateDefaultBackground{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateDefaultBackground) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateDefaultBackground
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateDefaultBackground) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
