// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateMessageIsPinned struct {
	Filter   filters.UpdateMessageIsPinned
	Response func(ctx *ext.Context) error
}

func NewUpdateMessageIsPinned(filter filters.UpdateMessageIsPinned, response func(ctx *ext.Context) error) *UpdateMessageIsPinned {
	return &UpdateMessageIsPinned{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageIsPinned) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateMessageIsPinned
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageIsPinned) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
