// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateGiftAuctionState struct {
	Filter   filters.UpdateGiftAuctionState
	Response func(ctx *ext.Context) error
}

func NewUpdateGiftAuctionState(filter filters.UpdateGiftAuctionState, response func(ctx *ext.Context) error) *UpdateGiftAuctionState {
	return &UpdateGiftAuctionState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGiftAuctionState) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateGiftAuctionState
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGiftAuctionState) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
