// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateNewChat struct {
	Filter   filters.UpdateNewChat
	Response func(ctx *ext.Context) error
}

func NewUpdateNewChat(filter filters.UpdateNewChat, response func(ctx *ext.Context) error) *UpdateNewChat {
	return &UpdateNewChat{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewChat) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateNewChat
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewChat) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
