// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateChatActiveStories struct {
	Filter   filters.UpdateChatActiveStories
	Response func(ctx *ext.Context) error
}

func NewUpdateChatActiveStories(filter filters.UpdateChatActiveStories, response func(ctx *ext.Context) error) *UpdateChatActiveStories {
	return &UpdateChatActiveStories{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatActiveStories) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateChatActiveStories
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatActiveStories) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
