// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot/ext"
	"github.com/AshokShau/gotdbot/ext/handlers/filters"
)

type UpdateChatUnreadMentionCount struct {
	Filter   filters.UpdateChatUnreadMentionCount
	Response func(ctx *ext.Context) error
}

func NewUpdateChatUnreadMentionCount(filter filters.UpdateChatUnreadMentionCount, response func(ctx *ext.Context) error) *UpdateChatUnreadMentionCount {
	return &UpdateChatUnreadMentionCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatUnreadMentionCount) CheckUpdate(ctx *ext.Context) bool {
	u := ctx.Update.UpdateChatUnreadMentionCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatUnreadMentionCount) HandleUpdate(ctx *ext.Context) error {
	return h.Response(ctx)
}
