// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers_test

import (
	"testing"
	"time"

	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers"
)

func TestGeneratedHandlers(t *testing.T) {
	c := &gotdbot.Client{}
	d := gotdbot.NewDispatcher(nil)

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAccentColors(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAccentColors{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAccentColors not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateActiveEmojiReactions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateActiveEmojiReactions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateActiveEmojiReactions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateActiveGiftAuctions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateActiveGiftAuctions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateActiveGiftAuctions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateActiveLiveLocationMessages(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateActiveLiveLocationMessages{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateActiveLiveLocationMessages not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateActiveNotifications(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateActiveNotifications{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateActiveNotifications not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAgeVerificationParameters(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAgeVerificationParameters{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAgeVerificationParameters not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAnimatedEmojiMessageClicked(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAnimatedEmojiMessageClicked{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAnimatedEmojiMessageClicked not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAnimationSearchParameters(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAnimationSearchParameters{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAnimationSearchParameters not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateApplicationRecaptchaVerificationRequired(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateApplicationRecaptchaVerificationRequired{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateApplicationRecaptchaVerificationRequired not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateApplicationVerificationRequired(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateApplicationVerificationRequired{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateApplicationVerificationRequired not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAttachmentMenuBots(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAttachmentMenuBots{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAttachmentMenuBots not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAuthorizationState(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAuthorizationState{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAuthorizationState not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAutosaveSettings(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAutosaveSettings{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAutosaveSettings not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateAvailableMessageEffects(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateAvailableMessageEffects{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateAvailableMessageEffects not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateBasicGroup(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateBasicGroup{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateBasicGroup not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateBasicGroupFullInfo(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateBasicGroupFullInfo{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateBasicGroupFullInfo not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateBusinessConnection(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateBusinessConnection{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateBusinessConnection not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateBusinessMessageEdited(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateBusinessMessageEdited{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateBusinessMessageEdited not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateBusinessMessagesDeleted(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateBusinessMessagesDeleted{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateBusinessMessagesDeleted not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateCall(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateCall{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateCall not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatAccentColors(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatAccentColors{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatAccentColors not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatAction(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatAction{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatAction not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatActionBar(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatActionBar{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatActionBar not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatActiveStories(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatActiveStories{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatActiveStories not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatAddedToList(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatAddedToList{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatAddedToList not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatAvailableReactions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatAvailableReactions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatAvailableReactions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatBackground(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatBackground{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatBackground not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatBlockList(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatBlockList{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatBlockList not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatBoost(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatBoost{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatBoost not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatBusinessBotManageBar(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatBusinessBotManageBar{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatBusinessBotManageBar not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatDefaultDisableNotification(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatDefaultDisableNotification{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatDefaultDisableNotification not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatDraftMessage(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatDraftMessage{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatDraftMessage not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatEmojiStatus(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatEmojiStatus{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatEmojiStatus not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatFolders(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatFolders{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatFolders not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatHasProtectedContent(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatHasProtectedContent{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatHasProtectedContent not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatHasScheduledMessages(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatHasScheduledMessages{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatHasScheduledMessages not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatIsMarkedAsUnread(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatIsMarkedAsUnread{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatIsMarkedAsUnread not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatIsTranslatable(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatIsTranslatable{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatIsTranslatable not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatLastMessage(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatLastMessage{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatLastMessage not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatMember(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatMember{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatMember not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatMessageAutoDeleteTime(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatMessageAutoDeleteTime{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatMessageAutoDeleteTime not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatMessageSender(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatMessageSender{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatMessageSender not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatNotificationSettings(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatNotificationSettings{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatNotificationSettings not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatOnlineMemberCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatOnlineMemberCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatOnlineMemberCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatPendingJoinRequests(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatPendingJoinRequests{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatPendingJoinRequests not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatPermissions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatPermissions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatPermissions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatPhoto(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatPhoto{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatPhoto not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatPosition(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatPosition{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatPosition not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatReadInbox(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatReadInbox{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatReadInbox not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatReadOutbox(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatReadOutbox{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatReadOutbox not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatRemovedFromList(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatRemovedFromList{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatRemovedFromList not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatReplyMarkup(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatReplyMarkup{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatReplyMarkup not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatRevenueAmount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatRevenueAmount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatRevenueAmount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatTheme(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatTheme{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatTheme not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatTitle(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatTitle{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatTitle not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatUnreadMentionCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatUnreadMentionCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatUnreadMentionCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatUnreadPollVoteCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatUnreadPollVoteCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatUnreadPollVoteCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatUnreadReactionCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatUnreadReactionCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatUnreadReactionCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatVideoChat(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatVideoChat{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatVideoChat not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateChatViewAsTopics(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateChatViewAsTopics{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateChatViewAsTopics not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateConnectionState(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateConnectionState{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateConnectionState not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateContactCloseBirthdays(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateContactCloseBirthdays{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateContactCloseBirthdays not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateDefaultBackground(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateDefaultBackground{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateDefaultBackground not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateDefaultPaidReactionType(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateDefaultPaidReactionType{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateDefaultPaidReactionType not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateDefaultReactionType(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateDefaultReactionType{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateDefaultReactionType not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateDeleteMessages(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateDeleteMessages{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateDeleteMessages not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateDiceEmojis(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateDiceEmojis{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateDiceEmojis not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateDirectMessagesChatTopic(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateDirectMessagesChatTopic{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateDirectMessagesChatTopic not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateEmojiChatThemes(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateEmojiChatThemes{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateEmojiChatThemes not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFavoriteStickers(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFavoriteStickers{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFavoriteStickers not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFile(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFile{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFile not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFileAddedToDownloads(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFileAddedToDownloads{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFileAddedToDownloads not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFileDownload(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFileDownload{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFileDownload not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFileDownloads(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFileDownloads{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFileDownloads not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFileGenerationStart(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFileGenerationStart{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFileGenerationStart not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFileGenerationStop(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFileGenerationStop{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFileGenerationStop not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFileRemovedFromDownloads(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFileRemovedFromDownloads{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFileRemovedFromDownloads not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateForumTopic(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateForumTopic{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateForumTopic not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateForumTopicInfo(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateForumTopicInfo{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateForumTopicInfo not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateFreezeState(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateFreezeState{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateFreezeState not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGiftAuctionState(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGiftAuctionState{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGiftAuctionState not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCall(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCall{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCall not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCallMessageLevels(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCallMessageLevels{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCallMessageLevels not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCallMessagesDeleted(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCallMessagesDeleted{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCallMessagesDeleted not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCallMessageSendFailed(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCallMessageSendFailed{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCallMessageSendFailed not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCallParticipant(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCallParticipant{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCallParticipant not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCallParticipants(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCallParticipants{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCallParticipants not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateGroupCallVerificationState(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateGroupCallVerificationState{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateGroupCallVerificationState not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateHavePendingNotifications(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateHavePendingNotifications{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateHavePendingNotifications not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateInstalledStickerSets(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateInstalledStickerSets{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateInstalledStickerSets not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateLanguagePackStrings(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateLanguagePackStrings{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateLanguagePackStrings not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateLiveStoryTopDonors(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateLiveStoryTopDonors{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateLiveStoryTopDonors not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateManagedBot(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateManagedBot{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateManagedBot not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageContent(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageContent{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageContent not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageContentOpened(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageContentOpened{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageContentOpened not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageEdited(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageEdited{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageEdited not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageFactCheck(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageFactCheck{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageFactCheck not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageInteractionInfo(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageInteractionInfo{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageInteractionInfo not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageIsPinned(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageIsPinned{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageIsPinned not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageLiveLocationViewed(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageLiveLocationViewed{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageLiveLocationViewed not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageMentionRead(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageMentionRead{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageMentionRead not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageReaction(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageReaction{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageReaction not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageReactions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageReactions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageReactions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageSendAcknowledged(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageSendAcknowledged{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageSendAcknowledged not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageSendFailed(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageSendFailed{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageSendFailed not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageSendSucceeded(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageSendSucceeded{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageSendSucceeded not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageSuggestedPostInfo(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageSuggestedPostInfo{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageSuggestedPostInfo not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateMessageUnreadReactions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateMessageUnreadReactions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateMessageUnreadReactions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewBusinessCallbackQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewBusinessCallbackQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewBusinessCallbackQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewBusinessMessage(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewBusinessMessage{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewBusinessMessage not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewCallbackQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewCallbackQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewCallbackQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewCallSignalingData(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewCallSignalingData{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewCallSignalingData not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewChat(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewChat{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewChat not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewChatJoinRequest(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewChatJoinRequest{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewChatJoinRequest not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewChosenInlineResult(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewChosenInlineResult{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewChosenInlineResult not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewCustomEvent(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewCustomEvent{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewCustomEvent not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewCustomQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewCustomQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewCustomQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewGroupCallMessage(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewGroupCallMessage{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewGroupCallMessage not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewGroupCallPaidReaction(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewGroupCallPaidReaction{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewGroupCallPaidReaction not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewInlineCallbackQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewInlineCallbackQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewInlineCallbackQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewInlineQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewInlineQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewInlineQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewMessage(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewMessage{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewMessage not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewOauthRequest(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewOauthRequest{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewOauthRequest not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewPreCheckoutQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewPreCheckoutQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewPreCheckoutQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNewShippingQuery(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNewShippingQuery{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNewShippingQuery not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNotification(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNotification{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNotification not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateNotificationGroup(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateNotificationGroup{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateNotificationGroup not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateOption(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateOption{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateOption not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateOwnedStarCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateOwnedStarCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateOwnedStarCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateOwnedTonCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateOwnedTonCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateOwnedTonCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdatePaidMediaPurchased(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdatePaidMediaPurchased{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdatePaidMediaPurchased not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdatePendingTextMessage(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdatePendingTextMessage{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdatePendingTextMessage not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdatePoll(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdatePoll{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdatePoll not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdatePollAnswer(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdatePollAnswer{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdatePollAnswer not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateProfileAccentColors(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateProfileAccentColors{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateProfileAccentColors not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateQuickReplyShortcut(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateQuickReplyShortcut{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateQuickReplyShortcut not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateQuickReplyShortcutDeleted(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateQuickReplyShortcutDeleted{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateQuickReplyShortcutDeleted not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateQuickReplyShortcutMessages(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateQuickReplyShortcutMessages{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateQuickReplyShortcutMessages not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateQuickReplyShortcuts(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateQuickReplyShortcuts{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateQuickReplyShortcuts not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateReactionNotificationSettings(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateReactionNotificationSettings{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateReactionNotificationSettings not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateRecentStickers(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateRecentStickers{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateRecentStickers not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSavedAnimations(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSavedAnimations{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSavedAnimations not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSavedMessagesTags(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSavedMessagesTags{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSavedMessagesTags not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSavedMessagesTopic(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSavedMessagesTopic{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSavedMessagesTopic not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSavedMessagesTopicCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSavedMessagesTopicCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSavedMessagesTopicCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSavedNotificationSounds(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSavedNotificationSounds{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSavedNotificationSounds not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateScopeNotificationSettings(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateScopeNotificationSettings{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateScopeNotificationSettings not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSecretChat(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSecretChat{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSecretChat not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateServiceNotification(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateServiceNotification{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateServiceNotification not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSpeechRecognitionTrial(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSpeechRecognitionTrial{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSpeechRecognitionTrial not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSpeedLimitNotification(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSpeedLimitNotification{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSpeedLimitNotification not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStakeDiceState(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStakeDiceState{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStakeDiceState not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStarRevenueStatus(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStarRevenueStatus{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStarRevenueStatus not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStickerSet(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStickerSet{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStickerSet not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStory(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStory{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStory not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStoryDeleted(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStoryDeleted{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStoryDeleted not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStoryListChatCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStoryListChatCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStoryListChatCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStoryPostFailed(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStoryPostFailed{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStoryPostFailed not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStoryPostSucceeded(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStoryPostSucceeded{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStoryPostSucceeded not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateStoryStealthMode(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateStoryStealthMode{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateStoryStealthMode not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSuggestedActions(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSuggestedActions{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSuggestedActions not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSupergroup(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSupergroup{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSupergroup not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateSupergroupFullInfo(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateSupergroupFullInfo{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateSupergroupFullInfo not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateTermsOfService(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateTermsOfService{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateTermsOfService not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateTextCompositionStyles(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateTextCompositionStyles{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateTextCompositionStyles not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateTonRevenueStatus(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateTonRevenueStatus{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateTonRevenueStatus not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateTopicMessageCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateTopicMessageCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateTopicMessageCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateTrendingStickerSets(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateTrendingStickerSets{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateTrendingStickerSets not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateTrustedMiniAppBots(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateTrustedMiniAppBots{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateTrustedMiniAppBots not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUnconfirmedSession(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUnconfirmedSession{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUnconfirmedSession not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUnreadChatCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUnreadChatCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUnreadChatCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUnreadMessageCount(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUnreadMessageCount{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUnreadMessageCount not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUser(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUser{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUser not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUserFullInfo(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUserFullInfo{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUserFullInfo not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUserPrivacySettingRules(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUserPrivacySettingRules{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUserPrivacySettingRules not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateUserStatus(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateUserStatus{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateUserStatus not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateVideoPublished(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateVideoPublished{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateVideoPublished not called")
		}
	}()

	func() {
		called := make(chan bool, 1)
		h := handlers.NewUpdateWebAppMessageSent(nil, func(b *gotdbot.Client, ctx *gotdbot.Context) error {
			called <- true
			return nil
		})
		d.AddHandler(h)
		d.ProcessUpdate(c, &gotdbot.UpdateWebAppMessageSent{})
		select {
		case <-called:
		case <-time.After(100 * time.Millisecond):
			t.Errorf("Handler for UpdateWebAppMessageSent not called")
		}
	}()

}
