// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateNewMessage struct {
	Filter   filters.UpdateNewMessage
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateNewMessage(filter filters.UpdateNewMessage, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateNewMessage {
	return &UpdateNewMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewMessage) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewMessage
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewMessage) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
