// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateNewInlineQuery struct {
	Filter   filters.UpdateNewInlineQuery
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateNewInlineQuery(filter filters.UpdateNewInlineQuery, response func(ctx *gotdbot.Context) error) *UpdateNewInlineQuery {
	return &UpdateNewInlineQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewInlineQuery) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewInlineQuery
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewInlineQuery) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
