// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageInteractionInfo struct {
	Filter   filters.UpdateMessageInteractionInfo
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateMessageInteractionInfo(filter filters.UpdateMessageInteractionInfo, response func(ctx *gotdbot.Context) error) *UpdateMessageInteractionInfo {
	return &UpdateMessageInteractionInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageInteractionInfo) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageInteractionInfo
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageInteractionInfo) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
