// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateFavoriteStickers The list of favorite stickers was updated
type UpdateFavoriteStickers struct {
	Filter   filters.UpdateFavoriteStickers
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateFavoriteStickers creates a new UpdateFavoriteStickers
func NewUpdateFavoriteStickers(filter filters.UpdateFavoriteStickers, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateFavoriteStickers {
	return &UpdateFavoriteStickers{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFavoriteStickers) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateFavoriteStickers
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFavoriteStickers) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
