// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageEdited struct {
	Filter   filters.UpdateMessageEdited
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateMessageEdited(filter filters.UpdateMessageEdited, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateMessageEdited {
	return &UpdateMessageEdited{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageEdited) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageEdited
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageEdited) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
