// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageReaction struct {
	Filter   filters.UpdateMessageReaction
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateMessageReaction(filter filters.UpdateMessageReaction, response func(ctx *gotdbot.Context) error) *UpdateMessageReaction {
	return &UpdateMessageReaction{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageReaction) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageReaction
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageReaction) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
