// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGiftAuctionState State of a gift auction was updated
type UpdateGiftAuctionState struct {
	Filter   filters.UpdateGiftAuctionState
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateGiftAuctionState creates a new UpdateGiftAuctionState
func NewUpdateGiftAuctionState(filter filters.UpdateGiftAuctionState, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateGiftAuctionState {
	return &UpdateGiftAuctionState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGiftAuctionState) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateGiftAuctionState
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGiftAuctionState) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
