// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateStoryStealthMode struct {
	Filter   filters.UpdateStoryStealthMode
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateStoryStealthMode(filter filters.UpdateStoryStealthMode, response func(ctx *gotdbot.Context) error) *UpdateStoryStealthMode {
	return &UpdateStoryStealthMode{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStoryStealthMode) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateStoryStealthMode
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStoryStealthMode) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
