// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSavedMessagesTopicCount struct {
	Filter   filters.UpdateSavedMessagesTopicCount
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateSavedMessagesTopicCount(filter filters.UpdateSavedMessagesTopicCount, response func(ctx *gotdbot.Context) error) *UpdateSavedMessagesTopicCount {
	return &UpdateSavedMessagesTopicCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedMessagesTopicCount) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSavedMessagesTopicCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedMessagesTopicCount) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
