// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatUnreadPollVoteCount The chat unread_poll_vote_count has changed
type UpdateChatUnreadPollVoteCount struct {
	Filter   filters.UpdateChatUnreadPollVoteCount
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateChatUnreadPollVoteCount creates a new UpdateChatUnreadPollVoteCount
func NewUpdateChatUnreadPollVoteCount(filter filters.UpdateChatUnreadPollVoteCount, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatUnreadPollVoteCount {
	return &UpdateChatUnreadPollVoteCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatUnreadPollVoteCount) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatUnreadPollVoteCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatUnreadPollVoteCount) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
