// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateAccentColors struct {
	Filter   filters.UpdateAccentColors
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateAccentColors(filter filters.UpdateAccentColors, response func(ctx *gotdbot.Context) error) *UpdateAccentColors {
	return &UpdateAccentColors{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAccentColors) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateAccentColors
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAccentColors) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
