// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateWebAppMessageSent struct {
	Filter   filters.UpdateWebAppMessageSent
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateWebAppMessageSent(filter filters.UpdateWebAppMessageSent, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateWebAppMessageSent {
	return &UpdateWebAppMessageSent{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateWebAppMessageSent) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateWebAppMessageSent
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateWebAppMessageSent) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
