// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateAnimatedEmojiMessageClicked struct {
	Filter   filters.UpdateAnimatedEmojiMessageClicked
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateAnimatedEmojiMessageClicked(filter filters.UpdateAnimatedEmojiMessageClicked, response func(ctx *gotdbot.Context) error) *UpdateAnimatedEmojiMessageClicked {
	return &UpdateAnimatedEmojiMessageClicked{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAnimatedEmojiMessageClicked) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateAnimatedEmojiMessageClicked
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAnimatedEmojiMessageClicked) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
