// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateFileGenerationStart struct {
	Filter   filters.UpdateFileGenerationStart
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateFileGenerationStart(filter filters.UpdateFileGenerationStart, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateFileGenerationStart {
	return &UpdateFileGenerationStart{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFileGenerationStart) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateFileGenerationStart
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFileGenerationStart) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
