// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSupergroup struct {
	Filter   filters.UpdateSupergroup
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateSupergroup(filter filters.UpdateSupergroup, response func(ctx *gotdbot.Context) error) *UpdateSupergroup {
	return &UpdateSupergroup{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSupergroup) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSupergroup
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSupergroup) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
