// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatActionBar struct {
	Filter   filters.UpdateChatActionBar
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatActionBar(filter filters.UpdateChatActionBar, response func(ctx *gotdbot.Context) error) *UpdateChatActionBar {
	return &UpdateChatActionBar{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatActionBar) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatActionBar
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatActionBar) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
