// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatUnreadReactionCount struct {
	Filter   filters.UpdateChatUnreadReactionCount
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatUnreadReactionCount(filter filters.UpdateChatUnreadReactionCount, response func(ctx *gotdbot.Context) error) *UpdateChatUnreadReactionCount {
	return &UpdateChatUnreadReactionCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatUnreadReactionCount) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatUnreadReactionCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatUnreadReactionCount) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
