// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateFileDownload struct {
	Filter   filters.UpdateFileDownload
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateFileDownload(filter filters.UpdateFileDownload, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateFileDownload {
	return &UpdateFileDownload{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFileDownload) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateFileDownload
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFileDownload) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
