// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatMember struct {
	Filter   filters.UpdateChatMember
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatMember(filter filters.UpdateChatMember, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatMember {
	return &UpdateChatMember{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatMember) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatMember
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatMember) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
