// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatIsMarkedAsUnread struct {
	Filter   filters.UpdateChatIsMarkedAsUnread
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatIsMarkedAsUnread(filter filters.UpdateChatIsMarkedAsUnread, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatIsMarkedAsUnread {
	return &UpdateChatIsMarkedAsUnread{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatIsMarkedAsUnread) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatIsMarkedAsUnread
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatIsMarkedAsUnread) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
