// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateStoryListChatCount struct {
	Filter   filters.UpdateStoryListChatCount
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateStoryListChatCount(filter filters.UpdateStoryListChatCount, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateStoryListChatCount {
	return &UpdateStoryListChatCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStoryListChatCount) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateStoryListChatCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStoryListChatCount) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
