// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateStoryPostSucceeded struct {
	Filter   filters.UpdateStoryPostSucceeded
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateStoryPostSucceeded(filter filters.UpdateStoryPostSucceeded, response func(ctx *gotdbot.Context) error) *UpdateStoryPostSucceeded {
	return &UpdateStoryPostSucceeded{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStoryPostSucceeded) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateStoryPostSucceeded
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStoryPostSucceeded) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
