// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateGroupCall struct {
	Filter   filters.UpdateGroupCall
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateGroupCall(filter filters.UpdateGroupCall, response func(ctx *gotdbot.Context) error) *UpdateGroupCall {
	return &UpdateGroupCall{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCall) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateGroupCall
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCall) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
