// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateTermsOfService struct {
	Filter   filters.UpdateTermsOfService
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateTermsOfService(filter filters.UpdateTermsOfService, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateTermsOfService {
	return &UpdateTermsOfService{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTermsOfService) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateTermsOfService
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTermsOfService) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
