// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateActiveLiveLocationMessages struct {
	Filter   filters.UpdateActiveLiveLocationMessages
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateActiveLiveLocationMessages(filter filters.UpdateActiveLiveLocationMessages, response func(ctx *gotdbot.Context) error) *UpdateActiveLiveLocationMessages {
	return &UpdateActiveLiveLocationMessages{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateActiveLiveLocationMessages) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateActiveLiveLocationMessages
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateActiveLiveLocationMessages) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
