// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateRecentStickers struct {
	Filter   filters.UpdateRecentStickers
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateRecentStickers(filter filters.UpdateRecentStickers, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateRecentStickers {
	return &UpdateRecentStickers{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateRecentStickers) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateRecentStickers
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateRecentStickers) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
