// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateTrustedMiniAppBots Lists of bots which Mini Apps must be allowed to read text from clipboard and must be opened without a warning
type UpdateTrustedMiniAppBots struct {
	Filter   filters.UpdateTrustedMiniAppBots
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateTrustedMiniAppBots creates a new UpdateTrustedMiniAppBots
func NewUpdateTrustedMiniAppBots(filter filters.UpdateTrustedMiniAppBots, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateTrustedMiniAppBots {
	return &UpdateTrustedMiniAppBots{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTrustedMiniAppBots) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateTrustedMiniAppBots
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTrustedMiniAppBots) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
