// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateAutosaveSettings struct {
	Filter   filters.UpdateAutosaveSettings
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateAutosaveSettings(filter filters.UpdateAutosaveSettings, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateAutosaveSettings {
	return &UpdateAutosaveSettings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAutosaveSettings) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateAutosaveSettings
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAutosaveSettings) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
