// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateQuickReplyShortcutMessages struct {
	Filter   filters.UpdateQuickReplyShortcutMessages
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateQuickReplyShortcutMessages(filter filters.UpdateQuickReplyShortcutMessages, response func(ctx *gotdbot.Context) error) *UpdateQuickReplyShortcutMessages {
	return &UpdateQuickReplyShortcutMessages{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateQuickReplyShortcutMessages) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateQuickReplyShortcutMessages
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateQuickReplyShortcutMessages) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
