// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSpeedLimitNotification Download or upload file speed for the user was limited, but it can be restored by subscription to Telegram Premium. The notification can be postponed until a being downloaded or uploaded file is visible to the user.
type UpdateSpeedLimitNotification struct {
	Filter   filters.UpdateSpeedLimitNotification
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateSpeedLimitNotification creates a new UpdateSpeedLimitNotification
func NewUpdateSpeedLimitNotification(filter filters.UpdateSpeedLimitNotification, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateSpeedLimitNotification {
	return &UpdateSpeedLimitNotification{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSpeedLimitNotification) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSpeedLimitNotification
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSpeedLimitNotification) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
