// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateStickerSet struct {
	Filter   filters.UpdateStickerSet
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateStickerSet(filter filters.UpdateStickerSet, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateStickerSet {
	return &UpdateStickerSet{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStickerSet) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateStickerSet
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStickerSet) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
