// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateNewCallbackQuery struct {
	Filter   filters.UpdateNewCallbackQuery
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateNewCallbackQuery(filter filters.UpdateNewCallbackQuery, response func(ctx *gotdbot.Context) error) *UpdateNewCallbackQuery {
	return &UpdateNewCallbackQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewCallbackQuery) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewCallbackQuery
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewCallbackQuery) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
