// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdatePaidMediaPurchased struct {
	Filter   filters.UpdatePaidMediaPurchased
	Response func(ctx *gotdbot.Context) error
}

func NewUpdatePaidMediaPurchased(filter filters.UpdatePaidMediaPurchased, response func(ctx *gotdbot.Context) error) *UpdatePaidMediaPurchased {
	return &UpdatePaidMediaPurchased{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdatePaidMediaPurchased) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdatePaidMediaPurchased
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdatePaidMediaPurchased) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
