// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateLiveStoryTopDonors The list of top donors in live story group call has changed
type UpdateLiveStoryTopDonors struct {
	Filter   filters.UpdateLiveStoryTopDonors
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateLiveStoryTopDonors creates a new UpdateLiveStoryTopDonors
func NewUpdateLiveStoryTopDonors(filter filters.UpdateLiveStoryTopDonors, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateLiveStoryTopDonors {
	return &UpdateLiveStoryTopDonors{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateLiveStoryTopDonors) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateLiveStoryTopDonors
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateLiveStoryTopDonors) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
