// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatIsTranslatable Translation of chat messages was enabled or disabled
type UpdateChatIsTranslatable struct {
	Filter   filters.UpdateChatIsTranslatable
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateChatIsTranslatable creates a new UpdateChatIsTranslatable
func NewUpdateChatIsTranslatable(filter filters.UpdateChatIsTranslatable, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatIsTranslatable {
	return &UpdateChatIsTranslatable{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatIsTranslatable) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatIsTranslatable
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatIsTranslatable) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
