// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateBusinessMessagesDeleted struct {
	Filter   filters.UpdateBusinessMessagesDeleted
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateBusinessMessagesDeleted(filter filters.UpdateBusinessMessagesDeleted, response func(ctx *gotdbot.Context) error) *UpdateBusinessMessagesDeleted {
	return &UpdateBusinessMessagesDeleted{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateBusinessMessagesDeleted) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateBusinessMessagesDeleted
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateBusinessMessagesDeleted) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
