// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatPendingJoinRequests struct {
	Filter   filters.UpdateChatPendingJoinRequests
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatPendingJoinRequests(filter filters.UpdateChatPendingJoinRequests, response func(ctx *gotdbot.Context) error) *UpdateChatPendingJoinRequests {
	return &UpdateChatPendingJoinRequests{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatPendingJoinRequests) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatPendingJoinRequests
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatPendingJoinRequests) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
