// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatAction struct {
	Filter   filters.UpdateChatAction
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatAction(filter filters.UpdateChatAction, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatAction {
	return &UpdateChatAction{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatAction) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatAction
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatAction) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
