// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatFolders struct {
	Filter   filters.UpdateChatFolders
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatFolders(filter filters.UpdateChatFolders, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatFolders {
	return &UpdateChatFolders{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatFolders) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatFolders
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatFolders) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
