// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSupergroupFullInfo struct {
	Filter   filters.UpdateSupergroupFullInfo
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateSupergroupFullInfo(filter filters.UpdateSupergroupFullInfo, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateSupergroupFullInfo {
	return &UpdateSupergroupFullInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSupergroupFullInfo) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSupergroupFullInfo
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSupergroupFullInfo) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
