// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateTopicMessageCount struct {
	Filter   filters.UpdateTopicMessageCount
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateTopicMessageCount(filter filters.UpdateTopicMessageCount, response func(ctx *gotdbot.Context) error) *UpdateTopicMessageCount {
	return &UpdateTopicMessageCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTopicMessageCount) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateTopicMessageCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTopicMessageCount) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
