// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatReplyMarkup struct {
	Filter   filters.UpdateChatReplyMarkup
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatReplyMarkup(filter filters.UpdateChatReplyMarkup, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatReplyMarkup {
	return &UpdateChatReplyMarkup{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatReplyMarkup) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatReplyMarkup
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatReplyMarkup) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
