// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateBasicGroupFullInfo Some data in basicGroupFullInfo has been changed
type UpdateBasicGroupFullInfo struct {
	Filter   filters.UpdateBasicGroupFullInfo
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateBasicGroupFullInfo creates a new UpdateBasicGroupFullInfo
func NewUpdateBasicGroupFullInfo(filter filters.UpdateBasicGroupFullInfo, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateBasicGroupFullInfo {
	return &UpdateBasicGroupFullInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateBasicGroupFullInfo) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateBasicGroupFullInfo
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateBasicGroupFullInfo) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
