// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageLiveLocationViewed struct {
	Filter   filters.UpdateMessageLiveLocationViewed
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateMessageLiveLocationViewed(filter filters.UpdateMessageLiveLocationViewed, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateMessageLiveLocationViewed {
	return &UpdateMessageLiveLocationViewed{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageLiveLocationViewed) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageLiveLocationViewed
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageLiveLocationViewed) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
