// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateStarRevenueStatus struct {
	Filter   filters.UpdateStarRevenueStatus
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateStarRevenueStatus(filter filters.UpdateStarRevenueStatus, response func(ctx *gotdbot.Context) error) *UpdateStarRevenueStatus {
	return &UpdateStarRevenueStatus{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateStarRevenueStatus) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateStarRevenueStatus
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateStarRevenueStatus) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
