// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSavedMessagesTopic struct {
	Filter   filters.UpdateSavedMessagesTopic
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateSavedMessagesTopic(filter filters.UpdateSavedMessagesTopic, response func(ctx *gotdbot.Context) error) *UpdateSavedMessagesTopic {
	return &UpdateSavedMessagesTopic{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedMessagesTopic) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSavedMessagesTopic
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedMessagesTopic) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
