// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateTonRevenueStatus struct {
	Filter   filters.UpdateTonRevenueStatus
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateTonRevenueStatus(filter filters.UpdateTonRevenueStatus, response func(ctx *gotdbot.Context) error) *UpdateTonRevenueStatus {
	return &UpdateTonRevenueStatus{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateTonRevenueStatus) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateTonRevenueStatus
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateTonRevenueStatus) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
