// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatAvailableReactions struct {
	Filter   filters.UpdateChatAvailableReactions
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatAvailableReactions(filter filters.UpdateChatAvailableReactions, response func(ctx *gotdbot.Context) error) *UpdateChatAvailableReactions {
	return &UpdateChatAvailableReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatAvailableReactions) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatAvailableReactions
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatAvailableReactions) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
