// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateNewPreCheckoutQuery struct {
	Filter   filters.UpdateNewPreCheckoutQuery
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateNewPreCheckoutQuery(filter filters.UpdateNewPreCheckoutQuery, response func(ctx *gotdbot.Context) error) *UpdateNewPreCheckoutQuery {
	return &UpdateNewPreCheckoutQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewPreCheckoutQuery) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewPreCheckoutQuery
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewPreCheckoutQuery) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
