// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateAnimationSearchParameters struct {
	Filter   filters.UpdateAnimationSearchParameters
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateAnimationSearchParameters(filter filters.UpdateAnimationSearchParameters, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateAnimationSearchParameters {
	return &UpdateAnimationSearchParameters{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateAnimationSearchParameters) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateAnimationSearchParameters
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateAnimationSearchParameters) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
