// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateFileDownloads struct {
	Filter   filters.UpdateFileDownloads
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateFileDownloads(filter filters.UpdateFileDownloads, response func(ctx *gotdbot.Context) error) *UpdateFileDownloads {
	return &UpdateFileDownloads{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFileDownloads) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateFileDownloads
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFileDownloads) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
