// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateDefaultPaidReactionType struct {
	Filter   filters.UpdateDefaultPaidReactionType
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateDefaultPaidReactionType(filter filters.UpdateDefaultPaidReactionType, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateDefaultPaidReactionType {
	return &UpdateDefaultPaidReactionType{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateDefaultPaidReactionType) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateDefaultPaidReactionType
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateDefaultPaidReactionType) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
