// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateGroupCallParticipants struct {
	Filter   filters.UpdateGroupCallParticipants
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateGroupCallParticipants(filter filters.UpdateGroupCallParticipants, response func(ctx *gotdbot.Context) error) *UpdateGroupCallParticipants {
	return &UpdateGroupCallParticipants{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallParticipants) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateGroupCallParticipants
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallParticipants) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
