// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateQuickReplyShortcuts struct {
	Filter   filters.UpdateQuickReplyShortcuts
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateQuickReplyShortcuts(filter filters.UpdateQuickReplyShortcuts, response func(ctx *gotdbot.Context) error) *UpdateQuickReplyShortcuts {
	return &UpdateQuickReplyShortcuts{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateQuickReplyShortcuts) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateQuickReplyShortcuts
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateQuickReplyShortcuts) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
