// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatTheme struct {
	Filter   filters.UpdateChatTheme
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatTheme(filter filters.UpdateChatTheme, response func(ctx *gotdbot.Context) error) *UpdateChatTheme {
	return &UpdateChatTheme{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatTheme) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatTheme
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatTheme) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
