// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatRevenueAmount struct {
	Filter   filters.UpdateChatRevenueAmount
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatRevenueAmount(filter filters.UpdateChatRevenueAmount, response func(ctx *gotdbot.Context) error) *UpdateChatRevenueAmount {
	return &UpdateChatRevenueAmount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatRevenueAmount) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatRevenueAmount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatRevenueAmount) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
