// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateUnreadMessageCount struct {
	Filter   filters.UpdateUnreadMessageCount
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateUnreadMessageCount(filter filters.UpdateUnreadMessageCount, response func(ctx *gotdbot.Context) error) *UpdateUnreadMessageCount {
	return &UpdateUnreadMessageCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUnreadMessageCount) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateUnreadMessageCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUnreadMessageCount) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
