// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateGroupCallMessageSendFailed struct {
	Filter   filters.UpdateGroupCallMessageSendFailed
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateGroupCallMessageSendFailed(filter filters.UpdateGroupCallMessageSendFailed, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateGroupCallMessageSendFailed {
	return &UpdateGroupCallMessageSendFailed{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallMessageSendFailed) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateGroupCallMessageSendFailed
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallMessageSendFailed) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
