// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateOwnedStarCount struct {
	Filter   filters.UpdateOwnedStarCount
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateOwnedStarCount(filter filters.UpdateOwnedStarCount, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateOwnedStarCount {
	return &UpdateOwnedStarCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateOwnedStarCount) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateOwnedStarCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateOwnedStarCount) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
