// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageSendAcknowledged struct {
	Filter   filters.UpdateMessageSendAcknowledged
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateMessageSendAcknowledged(filter filters.UpdateMessageSendAcknowledged, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateMessageSendAcknowledged {
	return &UpdateMessageSendAcknowledged{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSendAcknowledged) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageSendAcknowledged
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSendAcknowledged) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
