// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatVideoChat struct {
	Filter   filters.UpdateChatVideoChat
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatVideoChat(filter filters.UpdateChatVideoChat, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatVideoChat {
	return &UpdateChatVideoChat{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatVideoChat) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatVideoChat
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatVideoChat) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
