// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdatePaidMediaPurchased Paid media were purchased by a user; for bots only
type UpdatePaidMediaPurchased struct {
	Filter   filters.UpdatePaidMediaPurchased
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdatePaidMediaPurchased creates a new UpdatePaidMediaPurchased
func NewUpdatePaidMediaPurchased(filter filters.UpdatePaidMediaPurchased, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdatePaidMediaPurchased {
	return &UpdatePaidMediaPurchased{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdatePaidMediaPurchased) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdatePaidMediaPurchased
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdatePaidMediaPurchased) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
