// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatAddedToList struct {
	Filter   filters.UpdateChatAddedToList
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatAddedToList(filter filters.UpdateChatAddedToList, response func(ctx *gotdbot.Context) error) *UpdateChatAddedToList {
	return &UpdateChatAddedToList{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatAddedToList) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatAddedToList
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatAddedToList) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
