// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatIsTranslatable struct {
	Filter   filters.UpdateChatIsTranslatable
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatIsTranslatable(filter filters.UpdateChatIsTranslatable, response func(ctx *gotdbot.Context) error) *UpdateChatIsTranslatable {
	return &UpdateChatIsTranslatable{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatIsTranslatable) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatIsTranslatable
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatIsTranslatable) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
