// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateConnectionState The connection state has changed. This update must be used only to show a human-readable description of the connection state
type UpdateConnectionState struct {
	Filter   filters.UpdateConnectionState
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateConnectionState creates a new UpdateConnectionState
func NewUpdateConnectionState(filter filters.UpdateConnectionState, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateConnectionState {
	return &UpdateConnectionState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateConnectionState) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateConnectionState
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateConnectionState) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
