// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSuggestedActions struct {
	Filter   filters.UpdateSuggestedActions
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateSuggestedActions(filter filters.UpdateSuggestedActions, response func(ctx *gotdbot.Context) error) *UpdateSuggestedActions {
	return &UpdateSuggestedActions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSuggestedActions) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSuggestedActions
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSuggestedActions) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
