// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageReactions struct {
	Filter   filters.UpdateMessageReactions
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateMessageReactions(filter filters.UpdateMessageReactions, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateMessageReactions {
	return &UpdateMessageReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageReactions) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageReactions
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageReactions) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
