// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatTitle struct {
	Filter   filters.UpdateChatTitle
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatTitle(filter filters.UpdateChatTitle, response func(ctx *gotdbot.Context) error) *UpdateChatTitle {
	return &UpdateChatTitle{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatTitle) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatTitle
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatTitle) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
