// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageSendFailed struct {
	Filter   filters.UpdateMessageSendFailed
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateMessageSendFailed(filter filters.UpdateMessageSendFailed, response func(ctx *gotdbot.Context) error) *UpdateMessageSendFailed {
	return &UpdateMessageSendFailed{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSendFailed) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageSendFailed
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSendFailed) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
