// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateNotificationGroup struct {
	Filter   filters.UpdateNotificationGroup
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateNotificationGroup(filter filters.UpdateNotificationGroup, response func(ctx *gotdbot.Context) error) *UpdateNotificationGroup {
	return &UpdateNotificationGroup{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNotificationGroup) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNotificationGroup
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNotificationGroup) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
