// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatBlockList struct {
	Filter   filters.UpdateChatBlockList
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatBlockList(filter filters.UpdateChatBlockList, response func(ctx *gotdbot.Context) error) *UpdateChatBlockList {
	return &UpdateChatBlockList{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatBlockList) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatBlockList
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatBlockList) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
