// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGroupCallParticipant Information about a group call participant was changed. The updates are sent only after the group call is received through getGroupCall and only if the call is joined or being joined
type UpdateGroupCallParticipant struct {
	Filter   filters.UpdateGroupCallParticipant
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateGroupCallParticipant creates a new UpdateGroupCallParticipant
func NewUpdateGroupCallParticipant(filter filters.UpdateGroupCallParticipant, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateGroupCallParticipant {
	return &UpdateGroupCallParticipant{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallParticipant) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateGroupCallParticipant
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallParticipant) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
