// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSpeedLimitNotification struct {
	Filter   filters.UpdateSpeedLimitNotification
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateSpeedLimitNotification(filter filters.UpdateSpeedLimitNotification, response func(ctx *gotdbot.Context) error) *UpdateSpeedLimitNotification {
	return &UpdateSpeedLimitNotification{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSpeedLimitNotification) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSpeedLimitNotification
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSpeedLimitNotification) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
