// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateVideoPublished An automatically scheduled message with video has been successfully sent after conversion
type UpdateVideoPublished struct {
	Filter   filters.UpdateVideoPublished
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateVideoPublished creates a new UpdateVideoPublished
func NewUpdateVideoPublished(filter filters.UpdateVideoPublished, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateVideoPublished {
	return &UpdateVideoPublished{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateVideoPublished) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateVideoPublished
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateVideoPublished) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
