// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateNewCallSignalingData struct {
	Filter   filters.UpdateNewCallSignalingData
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateNewCallSignalingData(filter filters.UpdateNewCallSignalingData, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateNewCallSignalingData {
	return &UpdateNewCallSignalingData{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewCallSignalingData) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewCallSignalingData
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewCallSignalingData) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
