// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatPosition The position of a chat in a chat list has changed. An updateChatLastMessage or updateChatDraftMessage update might be sent instead of the update
type UpdateChatPosition struct {
	Filter   filters.UpdateChatPosition
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateChatPosition creates a new UpdateChatPosition
func NewUpdateChatPosition(filter filters.UpdateChatPosition, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatPosition {
	return &UpdateChatPosition{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatPosition) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatPosition
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatPosition) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
