// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatOnlineMemberCount struct {
	Filter   filters.UpdateChatOnlineMemberCount
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatOnlineMemberCount(filter filters.UpdateChatOnlineMemberCount, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatOnlineMemberCount {
	return &UpdateChatOnlineMemberCount{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatOnlineMemberCount) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatOnlineMemberCount
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatOnlineMemberCount) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
