// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageUnreadReactions struct {
	Filter   filters.UpdateMessageUnreadReactions
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateMessageUnreadReactions(filter filters.UpdateMessageUnreadReactions, response func(ctx *gotdbot.Context) error) *UpdateMessageUnreadReactions {
	return &UpdateMessageUnreadReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageUnreadReactions) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageUnreadReactions
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageUnreadReactions) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
