// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageFactCheck struct {
	Filter   filters.UpdateMessageFactCheck
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateMessageFactCheck(filter filters.UpdateMessageFactCheck, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateMessageFactCheck {
	return &UpdateMessageFactCheck{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageFactCheck) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageFactCheck
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageFactCheck) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
