// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateUser struct {
	Filter   filters.UpdateUser
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateUser(filter filters.UpdateUser, response func(ctx *gotdbot.Context) error) *UpdateUser {
	return &UpdateUser{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUser) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateUser
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUser) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
