// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatMessageAutoDeleteTime struct {
	Filter   filters.UpdateChatMessageAutoDeleteTime
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateChatMessageAutoDeleteTime(filter filters.UpdateChatMessageAutoDeleteTime, response func(ctx *gotdbot.Context) error) *UpdateChatMessageAutoDeleteTime {
	return &UpdateChatMessageAutoDeleteTime{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatMessageAutoDeleteTime) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatMessageAutoDeleteTime
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatMessageAutoDeleteTime) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
