// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateFreezeState struct {
	Filter   filters.UpdateFreezeState
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateFreezeState(filter filters.UpdateFreezeState, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateFreezeState {
	return &UpdateFreezeState{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFreezeState) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateFreezeState
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFreezeState) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
