// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateUserStatus struct {
	Filter   filters.UpdateUserStatus
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateUserStatus(filter filters.UpdateUserStatus, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateUserStatus {
	return &UpdateUserStatus{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateUserStatus) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateUserStatus
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateUserStatus) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
