// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateGroupCallParticipants The list of group call participants that can send and receive encrypted call data has changed; for group calls not bound to a chat only
type UpdateGroupCallParticipants struct {
	Filter   filters.UpdateGroupCallParticipants
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateGroupCallParticipants creates a new UpdateGroupCallParticipants
func NewUpdateGroupCallParticipants(filter filters.UpdateGroupCallParticipants, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateGroupCallParticipants {
	return &UpdateGroupCallParticipants{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateGroupCallParticipants) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateGroupCallParticipants
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateGroupCallParticipants) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
