// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewChatJoinRequest A user sent a join request to a chat; for bots only
type UpdateNewChatJoinRequest struct {
	Filter   filters.UpdateNewChatJoinRequest
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateNewChatJoinRequest creates a new UpdateNewChatJoinRequest
func NewUpdateNewChatJoinRequest(filter filters.UpdateNewChatJoinRequest, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateNewChatJoinRequest {
	return &UpdateNewChatJoinRequest{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewChatJoinRequest) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewChatJoinRequest
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewChatJoinRequest) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
