// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateScopeNotificationSettings struct {
	Filter   filters.UpdateScopeNotificationSettings
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateScopeNotificationSettings(filter filters.UpdateScopeNotificationSettings, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateScopeNotificationSettings {
	return &UpdateScopeNotificationSettings{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateScopeNotificationSettings) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateScopeNotificationSettings
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateScopeNotificationSettings) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
