// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateChatLastMessage struct {
	Filter   filters.UpdateChatLastMessage
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateChatLastMessage(filter filters.UpdateChatLastMessage, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatLastMessage {
	return &UpdateChatLastMessage{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatLastMessage) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatLastMessage
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatLastMessage) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
