// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateFile struct {
	Filter   filters.UpdateFile
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateFile(filter filters.UpdateFile, response func(ctx *gotdbot.Context) error) *UpdateFile {
	return &UpdateFile{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateFile) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateFile
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateFile) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
