// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateActiveEmojiReactions struct {
	Filter   filters.UpdateActiveEmojiReactions
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateActiveEmojiReactions(filter filters.UpdateActiveEmojiReactions, response func(ctx *gotdbot.Context) error) *UpdateActiveEmojiReactions {
	return &UpdateActiveEmojiReactions{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateActiveEmojiReactions) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateActiveEmojiReactions
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateActiveEmojiReactions) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
