// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateMessageSuggestedPostInfo struct {
	Filter   filters.UpdateMessageSuggestedPostInfo
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

func NewUpdateMessageSuggestedPostInfo(filter filters.UpdateMessageSuggestedPostInfo, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateMessageSuggestedPostInfo {
	return &UpdateMessageSuggestedPostInfo{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateMessageSuggestedPostInfo) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateMessageSuggestedPostInfo
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateMessageSuggestedPostInfo) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
