// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateSavedMessagesTopic Basic information about a Saved Messages topic has changed. This update is guaranteed to come before the topic identifier is returned to the application
type UpdateSavedMessagesTopic struct {
	Filter   filters.UpdateSavedMessagesTopic
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateSavedMessagesTopic creates a new UpdateSavedMessagesTopic
func NewUpdateSavedMessagesTopic(filter filters.UpdateSavedMessagesTopic, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateSavedMessagesTopic {
	return &UpdateSavedMessagesTopic{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSavedMessagesTopic) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSavedMessagesTopic
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSavedMessagesTopic) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
