// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

type UpdateSecretChat struct {
	Filter   filters.UpdateSecretChat
	Response func(ctx *gotdbot.Context) error
}

func NewUpdateSecretChat(filter filters.UpdateSecretChat, response func(ctx *gotdbot.Context) error) *UpdateSecretChat {
	return &UpdateSecretChat{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateSecretChat) CheckUpdate(ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateSecretChat
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateSecretChat) HandleUpdate(ctx *gotdbot.Context) error {
	return h.Response(ctx)
}
