// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateChatHasProtectedContent A chat content was allowed or restricted for saving
type UpdateChatHasProtectedContent struct {
	Filter   filters.UpdateChatHasProtectedContent
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateChatHasProtectedContent creates a new UpdateChatHasProtectedContent
func NewUpdateChatHasProtectedContent(filter filters.UpdateChatHasProtectedContent, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateChatHasProtectedContent {
	return &UpdateChatHasProtectedContent{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateChatHasProtectedContent) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateChatHasProtectedContent
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateChatHasProtectedContent) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
