// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// Regen by running 'go generate' in the repo root.

package handlers

import (
	"github.com/AshokShau/gotdbot"
	"github.com/AshokShau/gotdbot/handlers/filters"
)

// UpdateNewGuestQuery A new incoming guest query; for bots only
type UpdateNewGuestQuery struct {
	Filter   filters.UpdateNewGuestQuery
	Response func(b *gotdbot.Client, ctx *gotdbot.Context) error
}

// NewUpdateNewGuestQuery creates a new UpdateNewGuestQuery
func NewUpdateNewGuestQuery(filter filters.UpdateNewGuestQuery, response func(b *gotdbot.Client, ctx *gotdbot.Context) error) *UpdateNewGuestQuery {
	return &UpdateNewGuestQuery{
		Filter:   filter,
		Response: response,
	}
}

func (h *UpdateNewGuestQuery) CheckUpdate(b *gotdbot.Client, ctx *gotdbot.Context) bool {
	u := ctx.Update.UpdateNewGuestQuery
	if u == nil {
		return false
	}
	if h.Filter == nil {
		return true
	}
	return h.Filter(u)
}

func (h *UpdateNewGuestQuery) HandleUpdate(b *gotdbot.Client, ctx *gotdbot.Context) error {
	return h.Response(b, ctx)
}
